/**
 * The import's write path, against a real PostgreSQL with PostGIS.
 *
 * What only a database can answer: that the conflict targets are the ones the
 * schema declares, that `(place, language, source)` really does make a GoWay
 * correction unaddressable by an OpenStreetMap refresh, and that the generated
 * `name_normalized` columns duplicate detection reads are the ones Postgres
 * computes rather than the ones TypeScript would have.
 *
 * This suite does not skip. See `db/__tests__/testDatabase.ts`.
 */

import '../../../__tests__/testEnv';
import { afterAll, beforeAll, describe, expect, it } from 'bun:test';
import { and, eq } from 'drizzle-orm';
import { uuidv7 } from '@oxy.so/db';
import { categoryCatalog, type OsmCategoryMapping } from '../../../categories/catalog';
import {
  SUITE_SETUP_TIMEOUT_MS,
  createSuiteDatabase,
  destroySuiteDatabase,
  type SuiteDatabase,
} from '../../../db/__tests__/testDatabase';
import { updatePlace, type PlaceActor } from '../../../db/places/placesRepository';
import { places, placesCapabilities, placesNames, placesSources } from '../../../db/schema';
import { apiAuthor } from '../../../__tests__/placesFixtures';
import { detectDuplicates } from '../duplicates';
import { toImportedPlace, type ImportedPlace } from '../placeRecord';
import { OSM_SOURCE, emptyWriteStats, writePlaceBatch } from '../writePlaces';

let suite: SuiteDatabase | null = null;
/** The migrated database's own OpenStreetMap mapping, read as a run reads it. */
let mapping: OsmCategoryMapping;

/** Whoever edits a place through the API in this suite. */
const CLEARER: PlaceActor = {
  author: apiAuthor('person-business'),
  assertedVerification: 'community_reported',
};

beforeAll(async () => {
  suite = await createSuiteDatabase();
  mapping = await categoryCatalog(suite.db);
}, SUITE_SETUP_TIMEOUT_MS);

afterAll(async () => {
  await destroySuiteDatabase(suite);
  suite = null;
});

function element(
  sourceId: string,
  tags: Record<string, string>,
  latitude = 41.385_1,
  longitude = 2.173_4,
): ImportedPlace {
  const [type, id] = sourceId.split('/');
  const place = toImportedPlace(
    (type ?? 'node') as 'node' | 'way' | 'relation',
    Number(id),
    latitude,
    longitude,
    new Map(Object.entries(tags)),
    mapping,
  );
  if (!place) throw new Error(`${sourceId} is not a POI`);
  return place;
}

async function importBatch(batch: ImportedPlace[], observedAt = new Date()) {
  const stats = emptyWriteStats();
  await writePlaceBatch(suite!.db, batch, observedAt, stats);
  return stats;
}

async function placeIdOf(sourceId: string): Promise<string> {
  const [row] = await suite!.db
    .select({ placeId: placesSources.placeId })
    .from(placesSources)
    .where(and(eq(placesSources.source, OSM_SOURCE), eq(placesSources.sourceId, sourceId)));
  if (!row) throw new Error(`${sourceId} was not linked`);
  return row.placeId;
}

describe('writePlaceBatch', () => {
  it('creates a place, its provenance and every translated name', async () => {
    const museum = element('way/188938001', {
      tourism: 'museum',
      name: 'Museu Picasso',
      'name:es': 'Museo Picasso',
      'name:en': 'Picasso Museum',
      'addr:city': 'Barcelona',
      'addr:country': 'es',
    });
    const stats = await importBatch([museum]);
    expect(stats.placesInserted).toBe(1);
    expect(stats.namesOffered).toBe(2);

    const placeId = await placeIdOf('way/188938001');
    const [row] = await suite!.db.select().from(places).where(eq(places.id, placeId));
    expect(row?.name).toBe('Museu Picasso');
    expect(row?.categories).toEqual(['culture.museum']);
    expect(row?.addressCountryCode).toBe('ES');
    // Generated by Postgres, and the only name form reconciliation compares.
    expect(row?.nameNormalized).toBe('museu picasso');

    const names = await suite!.db
      .select()
      .from(placesNames)
      .where(eq(placesNames.placeId, placeId));
    expect(names.map((name) => `${name.language}:${name.name}:${name.source}`).sort()).toEqual([
      'en:Picasso Museum:openstreetmap',
      'es:Museo Picasso:openstreetmap',
    ]);
  });

  it('is idempotent: a second identical run writes no place row at all', async () => {
    const bar = element('node/1001', { amenity: 'bar', name: 'Bar Pepe' });
    await importBatch([bar]);
    const second = await importBatch([bar]);
    expect(second.placesInserted).toBe(0);
    expect(second.placesUpdated).toBe(0);
    expect(second.placesUnchanged).toBe(1);
  });

  it('refreshes a fact the source changed', async () => {
    const before = element('node/1002', { amenity: 'cafe', name: 'Cafè Vell' });
    await importBatch([before]);
    const after = element('node/1002', { amenity: 'cafe', name: 'Cafè Nou' });
    const stats = await importBatch([after]);
    expect(stats.placesUpdated).toBe(1);

    const placeId = await placeIdOf('node/1002');
    const [row] = await suite!.db
      .select({ name: places.name })
      .from(places)
      .where(eq(places.id, placeId));
    expect(row?.name).toBe('Cafè Nou');
  });

  it('leaves a GoWay correction to the default name alone', async () => {
    const before = element('node/1003', { amenity: 'cafe', name: 'CAFE MAL ESCRIT' });
    await importBatch([before]);
    const placeId = await placeIdOf('node/1003');
    await suite!.db.update(places).set({ name: 'Cafè Ben Escrit' }).where(eq(places.id, placeId));

    const after = element('node/1003', { amenity: 'cafe', name: 'CAFE MAL ESCRIT UN ALTRE COP' });
    const stats = await importBatch([after]);
    expect(stats.placesUpdated).toBe(0);

    const [row] = await suite!.db
      .select({ name: places.name })
      .from(places)
      .where(eq(places.id, placeId));
    expect(row?.name).toBe('Cafè Ben Escrit');
  });

  it('cannot address a goway name row, whatever it does to its own', async () => {
    const before = element('node/1004', {
      tourism: 'museum',
      name: 'Museu X',
      'name:es': 'Museo X',
    });
    await importBatch([before]);
    const placeId = await placeIdOf('node/1004');

    // A GoWay correction to the SAME language, exactly as the HTTP path writes it.
    await suite!.db.insert(placesNames).values({
      id: uuidv7(),
      placeId,
      language: 'es',
      name: 'Museo Equis',
      source: 'goway',
    });

    const after = element('node/1004', {
      tourism: 'museum',
      name: 'Museu X',
      'name:es': 'Museo X (OSM)',
    });
    await importBatch([after]);

    const names = await suite!.db
      .select({ name: placesNames.name, source: placesNames.source })
      .from(placesNames)
      .where(and(eq(placesNames.placeId, placeId), eq(placesNames.language, 'es')));
    expect(names.sort((left, right) => left.source.localeCompare(right.source))).toEqual([
      { name: 'Museo Equis', source: 'goway' },
      { name: 'Museo X (OSM)', source: 'openstreetmap' },
    ]);
  });

  it('refuses to move a name backward in time', async () => {
    const now = new Date();
    const older = new Date(now.getTime() - 86_400_000);
    await importBatch(
      [element('node/1005', { amenity: 'bar', name: 'Bar T', 'name:es': 'Bar Nuevo' })],
      now,
    );
    await importBatch(
      [element('node/1005', { amenity: 'bar', name: 'Bar T', 'name:es': 'Bar Viejo' })],
      older,
    );

    const placeId = await placeIdOf('node/1005');
    const [row] = await suite!.db
      .select({ name: placesNames.name })
      .from(placesNames)
      .where(and(eq(placesNames.placeId, placeId), eq(placesNames.language, 'es')));
    expect(row?.name).toBe('Bar Nuevo');
  });

  it('replaying an older extract does not overwrite what a newer one recorded', async () => {
    const now = new Date();
    const older = new Date(now.getTime() - 86_400_000);
    await importBatch([element('node/1007', { amenity: 'bar', name: 'Bar Ara' })], now);
    await importBatch([element('node/1007', { amenity: 'bar', name: 'Bar Abans' })], older);

    const [row] = await suite!.db
      .select({ sourceData: placesSources.sourceData, observedAt: placesSources.observedAt })
      .from(placesSources)
      .where(and(eq(placesSources.source, OSM_SOURCE), eq(placesSources.sourceId, 'node/1007')));
    // `source_data` is what the NEXT run compares against to tell a correction
    // from an untouched source fact, so letting a stale extract rewrite it
    // would make the merge believe the newer name was somebody's edit.
    expect(row?.sourceData?.normalized.name).toBe('Bar Ara');
    expect(row?.observedAt.getTime()).toBe(now.getTime());
  });

  it('joins a place another path already bound, rather than making a second one', async () => {
    // `(source, source_id)` is unique ACROSS `places_sources`, so an element the
    // import has never seen may still belong to a place somebody created by
    // hand. Matching on that pair is what makes the import deterministic: the
    // element IS that place, and a second row for it would be the duplication
    // this whole design exists to avoid.
    const existing = uuidv7();
    await suite!.db
      .insert(places)
      .values({ id: existing, name: 'Bar de la Carme', latitude: 41.1, longitude: 2.1 });
    await suite!.db.insert(placesSources).values({
      id: uuidv7(),
      placeId: existing,
      source: OSM_SOURCE,
      sourceId: 'node/1006',
    });

    const stats = await importBatch([
      element('node/1006', {
        amenity: 'cafe',
        name: 'BAR DE LA CARME',
        'name:es': 'Bar del Carmen',
      }),
    ]);
    expect(stats.placesInserted).toBe(0);
    expect(stats.conflicts).toBe(0);

    const bound = await suite!.db
      .select({ placeId: placesSources.placeId })
      .from(placesSources)
      .where(and(eq(placesSources.source, OSM_SOURCE), eq(placesSources.sourceId, 'node/1006')));
    expect(bound.map((row) => row.placeId)).toEqual([existing]);

    // …and with no record of what this source said last time, the merge fills
    // gaps and touches nothing else: the hand-written name stands.
    const [row] = await suite!.db
      .select({ name: places.name, categories: places.categories })
      .from(places)
      .where(eq(places.id, existing));
    expect(row?.name).toBe('Bar de la Carme');
    expect(row?.categories).toEqual(['food.cafe']);

    // The translation arrives regardless: `places_names` has no prior row for
    // `(place, es, openstreetmap)` to be cautious about.
    const names = await suite!.db
      .select({ name: placesNames.name })
      .from(placesNames)
      .where(and(eq(placesNames.placeId, existing), eq(placesNames.language, 'es')));
    expect(names).toEqual([{ name: 'Bar del Carmen' }]);
  });
});

describe('writePlaceBatch, beyond the name', () => {
  const RICH = {
    amenity: 'restaurant',
    name: 'Can Ric',
    opening_hours: 'Mo-Sa 13:00-16:00,20:00-23:30',
    wheelchair: 'yes',
    'payment:cards': 'yes',
    cuisine: 'catalan;tapas',
    'contact:instagram': 'canric',
    survey_date: '2026-01-01',
  };

  async function capabilitiesOf(placeId: string) {
    const rows = await suite!.db
      .select({
        key: placesCapabilities.key,
        value: placesCapabilities.value,
        verification: placesCapabilities.verification,
        placeSourceId: placesCapabilities.placeSourceId,
      })
      .from(placesCapabilities)
      .where(eq(placesCapabilities.placeId, placeId));
    return rows.sort((left, right) =>
      `${left.key}${left.verification}`.localeCompare(`${right.key}${right.verification}`),
    );
  }

  it('keeps every raw tag, the hours, the zone and the typed capabilities it reads', async () => {
    await importBatch([element('node/3001', RICH)]);
    const placeId = await placeIdOf('node/3001');

    const [place] = await suite!.db
      .select({
        openingHours: places.openingHours,
        timezone: places.timezone,
        categories: places.categories,
      })
      .from(places)
      .where(eq(places.id, placeId));
    expect(place?.categories).toEqual(['food.restaurant']);
    expect(place?.timezone).toBe('Europe/Madrid');
    expect(place?.openingHours?.raw).toBe('Mo-Sa 13:00-16:00,20:00-23:30');
    expect(place?.openingHours?.intervals).toHaveLength(12);

    const [source] = await suite!.db
      .select({ id: placesSources.id, sourceData: placesSources.sourceData })
      .from(placesSources)
      .where(and(eq(placesSources.source, OSM_SOURCE), eq(placesSources.sourceId, 'node/3001')));
    expect(source?.sourceData?.v).toBe(2);
    // Every tag — `survey_date` included, which nothing maps today.
    expect(source?.sourceData?.tags).toEqual(RICH);

    const capabilities = await capabilitiesOf(placeId);
    expect(
      capabilities.map(({ key, value, verification }) => ({ key, value, verification })),
    ).toEqual([
      { key: 'accessibility.wheelchair', value: 'yes', verification: 'external_source' },
      { key: 'food.cuisine', value: ['tapas', 'catalan'], verification: 'external_source' },
      { key: 'payments.cards', value: true, verification: 'external_source' },
      {
        key: 'social.instagram',
        value: 'https://www.instagram.com/canric',
        verification: 'external_source',
      },
    ]);
    // Each one tied to the element's own provenance row.
    expect(new Set(capabilities.map((capability) => capability.placeSourceId))).toEqual(
      new Set([source!.id]),
    );
  });

  it('is idempotent with everything: a second identical run changes no place row', async () => {
    const rich = element('node/3002', RICH);
    await importBatch([rich]);
    const placeId = await placeIdOf('node/3002');
    const [before] = await suite!.db
      .select({ updatedAt: places.updatedAt })
      .from(places)
      .where(eq(places.id, placeId));

    const second = await importBatch([rich], new Date(Date.now() + 60_000));
    expect(second.placesInserted).toBe(0);
    expect(second.placesUpdated).toBe(0);
    expect(second.placesUnchanged).toBe(1);
    expect(second.capabilitiesOffered).toBe(4);

    const [after] = await suite!.db
      .select({ updatedAt: places.updatedAt })
      .from(places)
      .where(eq(places.id, placeId));
    expect(after?.updatedAt.getTime()).toBe(before?.updatedAt.getTime());
    expect(await capabilitiesOf(placeId)).toHaveLength(4);
  });

  it('never overwrites a GoWay edit to the hours or the categories', async () => {
    await importBatch([element('node/3003', RICH)]);
    const placeId = await placeIdOf('node/3003');
    const corrected = {
      intervals: [{ day: 1 as const, opens: '12:00', closes: '15:00' }],
      raw: 'corrected by GoWay',
    };
    await suite!.db
      .update(places)
      .set({ openingHours: corrected, categories: ['food.restaurant', 'food.bar'] })
      .where(eq(places.id, placeId));

    const stats = await importBatch([
      element('node/3003', { ...RICH, amenity: 'cafe', opening_hours: 'Mo-Su 08:00-20:00' }),
    ]);
    expect(stats.placesUpdated).toBe(0);

    const [row] = await suite!.db
      .select({ openingHours: places.openingHours, categories: places.categories })
      .from(places)
      .where(eq(places.id, placeId));
    expect(row?.openingHours).toEqual(corrected);
    expect(row?.categories).toEqual(['food.restaurant', 'food.bar']);
  });

  it('keeps a field cleared through the API cleared, until OpenStreetMap says something new', async () => {
    const tags = { ...RICH, phone: '+34 930 000 000', 'addr:street': 'Carrer de Pere IV' };
    await importBatch([element('node/3005', tags)]);
    const placeId = await placeIdOf('node/3005');

    // The business clears the phone OpenStreetMap supplied: a PATCH with null.
    const cleared = await updatePlace(suite!.db, placeId, { contact: { phone: null } }, CLEARER);
    expect(cleared?.contact?.phone).toBeUndefined();

    // The next import repeats the old number. It is the number that was
    // cleared, so it stays cleared — and the place row is not touched.
    const repeated = await importBatch([element('node/3005', tags)], new Date(Date.now() + 60_000));
    expect(repeated.placesUpdated).toBe(0);
    const phoneOf = async () =>
      (
        await suite!.db
          .select({ phone: places.contactPhone })
          .from(places)
          .where(eq(places.id, placeId))
      )[0]?.phone;
    expect(await phoneOf()).toBeNull();

    // OpenStreetMap changes the number: new evidence the clear never saw.
    const changed = await importBatch(
      [element('node/3005', { ...tags, phone: '+34 930 222 222' })],
      new Date(Date.now() + 120_000),
    );
    expect(changed.placesUpdated).toBe(1);
    expect(await phoneOf()).toBe('+34 930 222 222');

    // Every other column it owns was untouched throughout.
    const [row] = await suite!.db
      .select({ street: places.addressStreet })
      .from(places)
      .where(eq(places.id, placeId));
    expect(row?.street).toBe('Carrer de Pere IV');
  });

  it('refreshes its own assertion and never touches a business or another source', async () => {
    await importBatch([element('node/3004', RICH)]);
    const placeId = await placeIdOf('node/3004');

    // The business says the opposite of OpenStreetMap, at its own tier.
    await suite!.db.insert(placesCapabilities).values({
      placeId,
      namespace: 'accessibility',
      capability: 'wheelchair',
      value: 'limited',
      verification: 'business_asserted',
    });
    // Another external source already holds the external tier for cards.
    const [other] = await suite!.db
      .insert(placesSources)
      .values({ placeId, source: 'mercaria', sourceId: 'location-1' })
      .returning({ id: placesSources.id });
    await suite!.db
      .update(placesCapabilities)
      .set({ value: false, placeSourceId: other!.id })
      .where(
        and(eq(placesCapabilities.placeId, placeId), eq(placesCapabilities.key, 'payments.cards')),
      );

    const stats = await importBatch([
      element('node/3004', { ...RICH, wheelchair: 'no', 'payment:cards': 'yes' }),
    ]);
    // A changed capability moves `updated_at` even with every column the same.
    expect(stats.placesUpdated).toBe(1);

    const byKey = new Map(
      (await capabilitiesOf(placeId)).map((row) => [`${row.key}/${row.verification}`, row.value]),
    );
    expect(byKey.get('accessibility.wheelchair/external_source')).toBe('no');
    expect(byKey.get('accessibility.wheelchair/business_asserted')).toBe('limited');
    // Mercaria's assertion is Mercaria's: OpenStreetMap cannot speak for it.
    expect(byKey.get('payments.cards/external_source')).toBe(false);
  });

  it('does not move a capability backward in time', async () => {
    const now = new Date();
    await importBatch([element('node/3005', { ...RICH, wheelchair: 'yes' })], now);
    await importBatch(
      [element('node/3005', { ...RICH, wheelchair: 'no' })],
      new Date(now.getTime() - 86_400_000),
    );
    const placeId = await placeIdOf('node/3005');
    const wheelchair = (await capabilitiesOf(placeId)).find(
      (row) => row.key === 'accessibility.wheelchair',
    );
    expect(wheelchair?.value).toBe('yes');
  });
});

describe('detectDuplicates', () => {
  it('files both name rules, each under the reason that is true of it', async () => {
    // Two pharmacies twenty metres apart with the same default name.
    await importBatch([
      element('node/2001', { amenity: 'pharmacy', name: 'Farmàcia Central' }, 41.5, 2.5),
      element('node/2002', { amenity: 'pharmacy', name: 'Farmàcia Central' }, 41.500_18, 2.5),
      // …and one with the same name five kilometres away, which is a branch.
      element('node/2003', { amenity: 'pharmacy', name: 'Farmàcia Central' }, 41.545, 2.5),
      // One museum recorded twice, each under a different language.
      element(
        'node/2004',
        { tourism: 'museum', name: 'Museu del Mar', 'name:es': 'Museo del Mar' },
        41.6,
        2.6,
      ),
      element('node/2005', { tourism: 'museum', name: 'Museo del Mar' }, 41.600_18, 2.6),
    ]);

    const stats = await detectDuplicates(suite!.db);
    expect(stats.proximityAndName).toBeGreaterThanOrEqual(1);
    expect(stats.proximityAndTranslatedName).toBeGreaterThanOrEqual(1);

    const rows = await suite!.client`
      SELECT reason FROM places_duplicate_candidates ORDER BY reason
    `;
    const reasons = rows.map((row) => row.reason as string);
    expect(reasons).toContain('proximity_and_name');
    expect(reasons).toContain('proximity_and_translated_name');

    // Nothing merged: both places are still there.
    const remaining = await suite!.client`SELECT count(*)::int AS count FROM places`;
    expect((remaining[0]?.count as number) ?? 0).toBeGreaterThan(5);
  });

  it('is idempotent: a second detection reopens nothing', async () => {
    const before = await suite!
      .client`SELECT count(*)::int AS count FROM places_duplicate_candidates`;
    await detectDuplicates(suite!.db);
    const after = await suite!
      .client`SELECT count(*)::int AS count FROM places_duplicate_candidates`;
    expect(after[0]?.count).toBe(before[0]?.count);
  });
});
