/**
 * The import's write path, against a real PostgreSQL with PostGIS.
 *
 * What only a database can answer: that the conflict targets are the ones the
 * schema declares, that `(place, language, source)` really does make a GoWay
 * correction unaddressable by an OpenStreetMap refresh, and that the generated
 * `name_normalized` columns duplicate detection reads are the ones Postgres
 * computes rather than the ones TypeScript would have.
 *
 * This suite does not skip. See `db/__tests__/testDatabase.ts`.
 */

import '../../../__tests__/testEnv';
import { afterAll, beforeAll, describe, expect, it } from 'bun:test';
import { and, eq } from 'drizzle-orm';
import { uuidv7 } from '@oxy.so/db';
import {
  SUITE_SETUP_TIMEOUT_MS,
  createSuiteDatabase,
  destroySuiteDatabase,
  type SuiteDatabase,
} from '../../../db/__tests__/testDatabase';
import { places, placesNames, placesSources } from '../../../db/schema';
import { detectDuplicates } from '../duplicates';
import { toImportedPlace, type ImportedPlace } from '../placeRecord';
import { OSM_SOURCE, emptyWriteStats, writePlaceBatch } from '../writePlaces';

let suite: SuiteDatabase | null = null;

beforeAll(async () => {
  suite = await createSuiteDatabase();
}, SUITE_SETUP_TIMEOUT_MS);

afterAll(async () => {
  await destroySuiteDatabase(suite);
  suite = null;
});

function element(
  sourceId: string,
  tags: Record<string, string>,
  latitude = 41.385_1,
  longitude = 2.173_4,
): ImportedPlace {
  const [type, id] = sourceId.split('/');
  const place = toImportedPlace(
    (type ?? 'node') as 'node' | 'way' | 'relation',
    Number(id),
    latitude,
    longitude,
    new Map(Object.entries(tags)),
  );
  if (!place) throw new Error(`${sourceId} is not a POI`);
  return place;
}

async function importBatch(batch: ImportedPlace[], observedAt = new Date()) {
  const stats = emptyWriteStats();
  await writePlaceBatch(suite!.db, batch, observedAt, stats);
  return stats;
}

async function placeIdOf(sourceId: string): Promise<string> {
  const [row] = await suite!.db
    .select({ placeId: placesSources.placeId })
    .from(placesSources)
    .where(and(eq(placesSources.source, OSM_SOURCE), eq(placesSources.sourceId, sourceId)));
  if (!row) throw new Error(`${sourceId} was not linked`);
  return row.placeId;
}

describe('writePlaceBatch', () => {
  it('creates a place, its provenance and every translated name', async () => {
    const museum = element('way/188938001', {
      tourism: 'museum',
      name: 'Museu Picasso',
      'name:es': 'Museo Picasso',
      'name:en': 'Picasso Museum',
      'addr:city': 'Barcelona',
      'addr:country': 'es',
    });
    const stats = await importBatch([museum]);
    expect(stats.placesInserted).toBe(1);
    expect(stats.namesOffered).toBe(2);

    const placeId = await placeIdOf('way/188938001');
    const [row] = await suite!.db.select().from(places).where(eq(places.id, placeId));
    expect(row?.name).toBe('Museu Picasso');
    expect(row?.categories).toEqual(['museum', 'culture']);
    expect(row?.addressCountryCode).toBe('ES');
    // Generated by Postgres, and the only name form reconciliation compares.
    expect(row?.nameNormalized).toBe('museu picasso');

    const names = await suite!.db
      .select()
      .from(placesNames)
      .where(eq(placesNames.placeId, placeId));
    expect(names.map((name) => `${name.language}:${name.name}:${name.source}`).sort()).toEqual([
      'en:Picasso Museum:openstreetmap',
      'es:Museo Picasso:openstreetmap',
    ]);
  });

  it('is idempotent: a second identical run writes no place row at all', async () => {
    const bar = element('node/1001', { amenity: 'bar', name: 'Bar Pepe' });
    await importBatch([bar]);
    const second = await importBatch([bar]);
    expect(second.placesInserted).toBe(0);
    expect(second.placesUpdated).toBe(0);
    expect(second.placesUnchanged).toBe(1);
  });

  it('refreshes a fact the source changed', async () => {
    const before = element('node/1002', { amenity: 'cafe', name: 'Cafè Vell' });
    await importBatch([before]);
    const after = element('node/1002', { amenity: 'cafe', name: 'Cafè Nou' });
    const stats = await importBatch([after]);
    expect(stats.placesUpdated).toBe(1);

    const placeId = await placeIdOf('node/1002');
    const [row] = await suite!.db.select({ name: places.name }).from(places).where(eq(places.id, placeId));
    expect(row?.name).toBe('Cafè Nou');
  });

  it('leaves a GoWay correction to the default name alone', async () => {
    const before = element('node/1003', { amenity: 'cafe', name: 'CAFE MAL ESCRIT' });
    await importBatch([before]);
    const placeId = await placeIdOf('node/1003');
    await suite!.db.update(places).set({ name: 'Cafè Ben Escrit' }).where(eq(places.id, placeId));

    const after = element('node/1003', { amenity: 'cafe', name: 'CAFE MAL ESCRIT UN ALTRE COP' });
    const stats = await importBatch([after]);
    expect(stats.placesUpdated).toBe(0);

    const [row] = await suite!.db.select({ name: places.name }).from(places).where(eq(places.id, placeId));
    expect(row?.name).toBe('Cafè Ben Escrit');
  });

  it('cannot address a goway name row, whatever it does to its own', async () => {
    const before = element('node/1004', { tourism: 'museum', name: 'Museu X', 'name:es': 'Museo X' });
    await importBatch([before]);
    const placeId = await placeIdOf('node/1004');

    // A GoWay correction to the SAME language, exactly as the HTTP path writes it.
    await suite!.db.insert(placesNames).values({
      id: uuidv7(),
      placeId,
      language: 'es',
      name: 'Museo Equis',
      source: 'goway',
    });

    const after = element('node/1004', { tourism: 'museum', name: 'Museu X', 'name:es': 'Museo X (OSM)' });
    await importBatch([after]);

    const names = await suite!.db
      .select({ name: placesNames.name, source: placesNames.source })
      .from(placesNames)
      .where(and(eq(placesNames.placeId, placeId), eq(placesNames.language, 'es')));
    expect(names.sort((left, right) => left.source.localeCompare(right.source))).toEqual([
      { name: 'Museo Equis', source: 'goway' },
      { name: 'Museo X (OSM)', source: 'openstreetmap' },
    ]);
  });

  it('refuses to move a name backward in time', async () => {
    const now = new Date();
    const older = new Date(now.getTime() - 86_400_000);
    await importBatch([element('node/1005', { amenity: 'bar', name: 'Bar T', 'name:es': 'Bar Nuevo' })], now);
    await importBatch([element('node/1005', { amenity: 'bar', name: 'Bar T', 'name:es': 'Bar Viejo' })], older);

    const placeId = await placeIdOf('node/1005');
    const [row] = await suite!.db
      .select({ name: placesNames.name })
      .from(placesNames)
      .where(and(eq(placesNames.placeId, placeId), eq(placesNames.language, 'es')));
    expect(row?.name).toBe('Bar Nuevo');
  });

  it('replaying an older extract does not overwrite what a newer one recorded', async () => {
    const now = new Date();
    const older = new Date(now.getTime() - 86_400_000);
    await importBatch([element('node/1007', { amenity: 'bar', name: 'Bar Ara' })], now);
    await importBatch([element('node/1007', { amenity: 'bar', name: 'Bar Abans' })], older);

    const [row] = await suite!.db
      .select({ sourceData: placesSources.sourceData, observedAt: placesSources.observedAt })
      .from(placesSources)
      .where(and(eq(placesSources.source, OSM_SOURCE), eq(placesSources.sourceId, 'node/1007')));
    // `source_data` is what the NEXT run compares against to tell a correction
    // from an untouched source fact, so letting a stale extract rewrite it
    // would make the merge believe the newer name was somebody's edit.
    expect((row?.sourceData as { name?: string } | null)?.name).toBe('Bar Ara');
    expect(row?.observedAt.getTime()).toBe(now.getTime());
  });

  it('joins a place another path already bound, rather than making a second one', async () => {
    // `(source, source_id)` is unique ACROSS `places_sources`, so an element the
    // import has never seen may still belong to a place somebody created by
    // hand. Matching on that pair is what makes the import deterministic: the
    // element IS that place, and a second row for it would be the duplication
    // this whole design exists to avoid.
    const existing = uuidv7();
    await suite!.db
      .insert(places)
      .values({ id: existing, name: 'Bar de la Carme', latitude: 41.1, longitude: 2.1 });
    await suite!.db.insert(placesSources).values({
      id: uuidv7(),
      placeId: existing,
      source: OSM_SOURCE,
      sourceId: 'node/1006',
    });

    const stats = await importBatch([
      element('node/1006', { amenity: 'cafe', name: 'BAR DE LA CARME', 'name:es': 'Bar del Carmen' }),
    ]);
    expect(stats.placesInserted).toBe(0);
    expect(stats.conflicts).toBe(0);

    const bound = await suite!.db
      .select({ placeId: placesSources.placeId })
      .from(placesSources)
      .where(and(eq(placesSources.source, OSM_SOURCE), eq(placesSources.sourceId, 'node/1006')));
    expect(bound.map((row) => row.placeId)).toEqual([existing]);

    // …and with no record of what this source said last time, the merge fills
    // gaps and touches nothing else: the hand-written name stands.
    const [row] = await suite!.db
      .select({ name: places.name, categories: places.categories })
      .from(places)
      .where(eq(places.id, existing));
    expect(row?.name).toBe('Bar de la Carme');
    expect(row?.categories).toEqual(['cafe', 'food_drink']);

    // The translation arrives regardless: `places_names` has no prior row for
    // `(place, es, openstreetmap)` to be cautious about.
    const names = await suite!.db
      .select({ name: placesNames.name })
      .from(placesNames)
      .where(and(eq(placesNames.placeId, existing), eq(placesNames.language, 'es')));
    expect(names).toEqual([{ name: 'Bar del Carmen' }]);
  });
});

describe('detectDuplicates', () => {
  it('files both name rules, each under the reason that is true of it', async () => {
    // Two pharmacies twenty metres apart with the same default name.
    await importBatch([
      element('node/2001', { amenity: 'pharmacy', name: 'Farmàcia Central' }, 41.5, 2.5),
      element('node/2002', { amenity: 'pharmacy', name: 'Farmàcia Central' }, 41.500_18, 2.5),
      // …and one with the same name five kilometres away, which is a branch.
      element('node/2003', { amenity: 'pharmacy', name: 'Farmàcia Central' }, 41.545, 2.5),
      // One museum recorded twice, each under a different language.
      element('node/2004', { tourism: 'museum', name: 'Museu del Mar', 'name:es': 'Museo del Mar' }, 41.6, 2.6),
      element('node/2005', { tourism: 'museum', name: 'Museo del Mar' }, 41.600_18, 2.6),
    ]);

    const stats = await detectDuplicates(suite!.db);
    expect(stats.proximityAndName).toBeGreaterThanOrEqual(1);
    expect(stats.proximityAndTranslatedName).toBeGreaterThanOrEqual(1);

    const rows = await suite!.client`
      SELECT reason FROM places_duplicate_candidates ORDER BY reason
    `;
    const reasons = rows.map((row) => row.reason as string);
    expect(reasons).toContain('proximity_and_name');
    expect(reasons).toContain('proximity_and_translated_name');

    // Nothing merged: both places are still there.
    const remaining = await suite!.client`SELECT count(*)::int AS count FROM places`;
    expect((remaining[0]?.count as number) ?? 0).toBeGreaterThan(5);
  });

  it('is idempotent: a second detection reopens nothing', async () => {
    const before = await suite!.client`SELECT count(*)::int AS count FROM places_duplicate_candidates`;
    await detectDuplicates(suite!.db);
    const after = await suite!.client`SELECT count(*)::int AS count FROM places_duplicate_candidates`;
    expect(after[0]?.count).toBe(before[0]?.count);
  });
});
