/**
 * The public contract, taken from its ONE definition.
 *
 * Every shape, closed value set, limit and schema below is defined in
 * `@goway/contracts` — zod 4 schemas the GoWay backend validates requests with
 * and this SDK parses responses with. That package is PRIVATE and never
 * published, so the build BUNDLES what this module reaches (declarations into
 * the `.d.ts`, values and schemas into the JavaScript) while `zod` itself stays
 * an ordinary dependency, and `scripts/smoke.mjs` fails the release if any
 * shipped file still names the private scope. Nothing here re-declares a type:
 * an SDK holding its own copy of `Place` would be a second source of truth.
 *
 * This is the only module in `src/` that imports the private package. The
 * schemas at the bottom are for the SDK's own use and are deliberately NOT
 * re-exported from `index.ts`: a consumer's contract is the TYPES and the
 * values, and a zod object in the public surface would make every internal
 * refinement a breaking change.
 */

export {
  // Places
  PLACE_STATUSES,
  WRITABLE_PLACE_STATUSES,
  PUBLISHED_PLACE_STATUSES,
  PLACE_VERIFICATION_STATES,
  CAPABILITY_VERIFICATIONS,
  PLACE_CLAIM_ROLES,
  PLACE_CLAIM_STATES,
  MAX_PLACE_LIST_LIMIT,
  MAX_PLACE_BATCH_SIZE,
  DEFAULT_PLACE_LIST_LIMIT,
  MAX_RADIUS_METERS,
  MAX_BOUNDS_SPAN_DEGREES,
  MAX_CLAIM_LIST_LIMIT,
  DEFAULT_CLAIM_LIST_LIMIT,
  MODERATED_PLACE_STATUSES,
  GONE_MERGED_INTO_DETAIL,
  // Revisions, reports and moderation
  PLACE_REVISION_ACTIONS,
  PLACE_REVISION_VISIBILITY,
  PUBLIC_PLACE_REVISION_ACTIONS,
  PLACE_REVISION_SOURCES,
  MAX_REVISION_LIST_LIMIT,
  DEFAULT_REVISION_LIST_LIMIT,
  PLACE_REPORT_REASONS,
  PLACE_REPORT_RESOLUTIONS,
  PLACE_REPORT_STATES,
  CLAIM_DECISION_STATES,
  CLAIM_DECISION_FROM,
  DUPLICATE_CANDIDATE_REASONS,
  DUPLICATE_CANDIDATE_STATES,
  MAX_MODERATION_LIST_LIMIT,
  DEFAULT_MODERATION_LIST_LIMIT,
  placeDisplayName,
  placeHasCapability,
  placeMatchesCapabilityFilter,
  splitCapabilityKey,
  strongestCapability,
  // Media and reviews
  PLACE_MEDIA_KINDS,
  BUSINESS_MEDIA_KINDS,
  PLACE_MEDIA_STATES,
  MODERATED_PLACE_MEDIA_STATES,
  PLACE_MEDIA_MIME_TYPES,
  MAX_MEDIA_CAPTION_LENGTH,
  MAX_MEDIA_ORDER_LENGTH,
  MAX_MEDIA_LIST_LIMIT,
  DEFAULT_MEDIA_LIST_LIMIT,
  PLACE_REVIEW_STATUSES,
  MODERATED_PLACE_REVIEW_STATUSES,
  REVIEW_SORTS,
  MIN_REVIEW_RATING,
  MAX_REVIEW_RATING,
  MAX_REVIEW_TITLE_LENGTH,
  MAX_REVIEW_BODY_LENGTH,
  MAX_REVIEW_REPLY_LENGTH,
  MAX_REVIEW_LIST_LIMIT,
  DEFAULT_REVIEW_LIST_LIMIT,
  CONTENT_REPORT_REASONS,
  MAX_DESCRIPTION_LENGTH,
  // Categories
  CATEGORIES,
  CATEGORY_ICONS,
  CATEGORY_KEYS,
  categoryDescendants,
  categoryLabel,
  categoryOf,
  categoryParent,
  categoryRoot,
  isCategoryKey,
  // Capabilities
  CAPABILITY_KEYS,
  CAPABILITY_GROUPS,
  CAPABILITY_VALUE_KINDS,
  capabilityGroupLabel,
  capabilityGroupOf,
  capabilityHolds,
  capabilityLabel,
  capabilityValueKind,
  capabilityValueLabel,
  isCapabilityKey,
  // Hours
  MAX_HOURS_EXCEPTION_DAYS,
  MAX_HOURS_EXCEPTION_INTERVALS,
  MAX_HOURS_EXCEPTION_LIST_LIMIT,
  DEFAULT_HOURS_EXCEPTION_LIST_LIMIT,
  openingStatusAt,
  // Labels
  LABEL_LANGUAGES,
  localizedLabel,
  matchLanguageTag,
  // Captures
  CAPTURE_ASSET_STATES,
  CAPTURE_CONTENT_HASH_ALGORITHM,
  CAPTURE_LOCATION_ORIGIN_RANK,
  CAPTURE_LOCATION_ORIGINS,
  CAPTURE_LOCATION_WITNESSES,
  CAPTURE_MEDIA_KINDS,
  CAPTURE_PRIVACY_STATES,
  CAPTURE_PROJECTIONS,
  CAPTURE_RETENTION_CLASSES,
  CAPTURE_SOURCES,
  DELETION_REASONS,
  RETENTION_CLASSES,
  RETENTION_REASONS,
  MAX_CAPTURE_LIST_LIMIT,
  DEFAULT_CAPTURE_LIST_LIMIT,
  // Street 3D
  STREET_COVERAGE_AREA_STATES,
  STREET_SCENE_ASSET_ROLES,
  STREET_SCENE_PROFILES,
  STREET_SCENE_REPORT_REASONS,
  // Search and directions
  SEARCH_RESULT_KINDS,
  SEARCH_SOURCES,
  SEARCH_MAX_LIMIT,
  SEARCH_MAX_DEPTH,
  MAX_SEARCH_QUERY_LENGTH,
  STRUCTURED_GEOCODE_FIELDS,
  TRAVEL_MODES,
  MANEUVER_TYPES,
  MAX_WAYPOINTS,
  // Geography, language, paging
  boundingBoxWidth,
  toGeoCoordinate,
  toGeoPosition,
  baseLanguageTag,
  normalizeLanguageTag,
  LANGUAGE_TAG_PATTERN,
  MAX_LANGUAGE_TAG_LENGTH,
  MAX_CURSOR_LENGTH,
  // Errors and the API root
  API_ERROR_CODES,
  API_ERROR_RETRYABLE,
  API_ERROR_STATUS,
  isApiErrorCode,
  GOWAY_API_BASE_PATH,
} from '@goway/contracts';

export type {
  // Geography
  GeoBoundingBox,
  GeoCoordinate,
  GeoGeometry,
  GeoJsonLineString,
  GeoJsonMultiPolygon,
  GeoJsonPoint,
  GeoJsonPolygon,
  GeoPosition,
  MapViewport,
  Meters,
  Seconds,
  // Paging and errors
  Page,
  ApiErrorBody,
  ApiErrorCode,
  ApiErrorDetails,
  // Places
  AccountClaimListQuery,
  CapabilityGroup,
  CapabilityKey,
  CapabilityValue,
  CapabilityValueKind,
  CapabilityVerification,
  Category,
  CategoryIcon,
  CategoryKey,
  CategoryPage,
  HoursExceptionListQuery,
  LabelLanguage,
  Labels,
  OpeningChange,
  OpeningFacts,
  OpeningStatus,
  PlaceHoursException,
  PlaceHoursExceptionInput,
  PlaceHoursExceptionPage,
  TimeRange,
  ClaimListQuery,
  NearbyPlacesQuery,
  OpeningHours,
  OpeningHoursInterval,
  Place,
  PlaceCapability,
  PlaceCapabilityAssertion,
  PlaceCapabilityInput,
  PlaceClaim,
  PlaceClaimInput,
  PlaceClaimPage,
  PlaceClaimRole,
  PlaceClaimState,
  PlaceContact,
  PlaceContactPatch,
  PlaceCreateInput,
  PlaceId,
  PlaceName,
  PlaceNameInput,
  PlaceBatch,
  PlaceBatchGone,
  PlaceBatchQuery,
  PlacePage,
  PlaceReadQuery,
  PlacesInBoundsQuery,
  PlaceSourceRef,
  PlaceSourceRefInput,
  PlaceStatus,
  PlaceUpdateInput,
  PlaceVerification,
  PlaceVerificationState,
  PlaceWithDistance,
  PlaceWithDistancePage,
  StructuredAddress,
  StructuredAddressPatch,
  WritablePlaceStatus,
  ModeratedPlaceStatus,
  // Revisions, reports and moderation
  PlaceRevision,
  PlaceRevisionAction,
  PlaceRevisionChange,
  PlaceRevisionPage,
  PlaceRevisionSource,
  PlaceRevisionVisibility,
  RevisionListQuery,
  RevisionValue,
  PlaceReport,
  PlaceReportInput,
  PlaceReportReason,
  PlaceReportResolution,
  PlaceReportResolutionInput,
  PlaceReportState,
  ModerationPlaceReport,
  ModerationPlaceReportPage,
  ModerationReportListQuery,
  ModerationPlaceRevision,
  ModerationPlaceRevisionPage,
  ModerationClaimListQuery,
  ModerationPlaceUpdateInput,
  ModerationCapabilityInput,
  ClaimDecisionInput,
  ClaimDecisionState,
  DuplicateCandidate,
  DuplicateCandidatePage,
  DuplicateCandidateReason,
  DuplicateCandidateState,
  DuplicateListQuery,
  DuplicateResolutionInput,
  // Media and reviews
  ContentReportInput,
  ContentReportReason,
  MediaListQuery,
  ModeratedPlaceMediaState,
  ModeratedPlaceReviewStatus,
  ModerationMediaInput,
  ModerationMediaListQuery,
  ModerationPlaceMedia,
  ModerationPlaceMediaPage,
  ModerationReviewInput,
  ModerationReviewListQuery,
  PlaceDescription,
  PlaceDescriptionInput,
  PlaceMedia,
  PlaceMediaInput,
  PlaceMediaKind,
  PlaceMediaOrderInput,
  PlaceMediaPage,
  PlaceMediaState,
  PlaceRating,
  PlaceReview,
  PlaceReviewInput,
  PlaceReviewPage,
  PlaceReviewReply,
  PlaceReviewReplyInput,
  PlaceReviewStatus,
  PlaceReviewWithStatus,
  PlaceReviewWithStatusPage,
  ReviewListQuery,
  ReviewSort,
  // Captures
  CaptureAnchor,
  CaptureAsset,
  CaptureAssetId,
  CaptureAssetInput,
  CaptureAssetPage,
  CaptureAssetState,
  CaptureCameraMetadata,
  CaptureContentHashAlgorithm,
  CaptureEquirectangularPolicy,
  CaptureListQuery,
  CaptureLocationEvidence,
  CaptureLocationEvidenceInput,
  CaptureLocationOrigin,
  CaptureLocationWitness,
  CaptureMediaKind,
  CaptureMediaObject,
  CapturePrivacyGate,
  CapturePrivacyState,
  CaptureProjection,
  CaptureRetentionClass,
  CaptureSession,
  CaptureSessionId,
  CaptureSessionInput,
  CaptureSessionPage,
  CaptureSource,
  CaptureUploadIntent,
  CaptureUploadPolicy,
  CaptureUploadTicket,
  DeletionReason,
  ExifGps,
  RetentionClass,
  RetentionReason,
  StoredObjectLifecycle,
  // Street 3D
  StreetCoverage,
  StreetCoverageArea,
  StreetCoverageAreaState,
  StreetCoverageQuery,
  StreetSceneAsset,
  StreetSceneAssetRole,
  StreetSceneFieldOfView,
  StreetSceneId,
  StreetSceneInitialView,
  StreetSceneManifest,
  StreetSceneNavigation,
  StreetSceneProfile,
  StreetSceneQuality,
  StreetSceneReport,
  StreetSceneReportInput,
  StreetSceneReportReason,
  StreetSceneSummary,
  StreetSceneViewpoint,
  StreetSceneWorldTransform,
  // Search
  ReverseGeocodeQuery,
  SearchQuery,
  SearchResult,
  SearchResultContext,
  SearchResultKind,
  SearchResults,
  SearchSource,
  StructuredGeocodeQuery,
  // Directions
  ManeuverType,
  Route,
  RouteLeg,
  RouteLocation,
  RouteManeuver,
  RouteRequest,
  RouteResponse,
  TravelMode,
} from '@goway/contracts';

// ── Schemas: the SDK's own use only, never re-exported from `index.ts` ───────

export {
  // Path parameters
  assetPathSchema,
  mediaPathSchema,
  reviewPathSchema,
  capabilityPathSchema,
  claimPathSchema,
  duplicatePathSchema,
  hoursExceptionPathSchema,
  placePathSchema,
  reportPathSchema,
  scenePathSchema,
  sessionPathSchema,
  // Requests
  accountClaimListQuerySchema,
  contentReportInputSchema,
  mediaListQuerySchema,
  moderationMediaInputSchema,
  moderationMediaListQuerySchema,
  moderationReviewInputSchema,
  moderationReviewListQuerySchema,
  placeMediaInputSchema,
  placeMediaOrderInputSchema,
  placeReviewInputSchema,
  placeReviewReplyInputSchema,
  reviewListQuerySchema,
  claimDecisionInputSchema,
  duplicateListQuerySchema,
  duplicateResolutionInputSchema,
  moderationCapabilityInputSchema,
  moderationCapabilityInputSchemaFor,
  moderationClaimListQuerySchema,
  moderationPlaceUpdateInputSchema,
  moderationReportListQuerySchema,
  placeReportInputSchema,
  placeReportResolutionInputSchema,
  revisionListQuerySchema,
  captureAssetInputSchema,
  captureListQuerySchema,
  captureSessionInputSchema,
  claimListQuerySchema,
  geoCoordinateSchema,
  hoursExceptionListQuerySchema,
  nearbyPlacesQuerySchema,
  placeCapabilityAssertionSchemaFor,
  placeHoursExceptionInputSchema,
  placeClaimInputSchema,
  placeCreateInputSchema,
  placeBatchQuerySchema,
  placeReadQuerySchema,
  placesInBoundsQuerySchema,
  placeUpdateInputSchema,
  reverseGeocodeQuerySchema,
  routeRequestSchema,
  searchParametersOf,
  searchParametersSchema,
  streetCoverageQuerySchema,
  streetSceneReportInputSchema,
  structuredGeocodeQuerySchema,
  // Responses
  moderationPlaceMediaPageSchema,
  moderationPlaceMediaSchema,
  placeMediaPageSchema,
  placeMediaSchema,
  placeReviewPageSchema,
  placeReviewSchema,
  placeReviewWithStatusPageSchema,
  placeReviewWithStatusSchema,
  duplicateCandidatePageSchema,
  duplicateCandidateSchema,
  moderationPlaceReportPageSchema,
  moderationPlaceReportSchema,
  moderationPlaceRevisionPageSchema,
  placeReportSchema,
  placeRevisionPageSchema,
  captureAssetPageSchema,
  captureAssetSchema,
  captureSessionPageSchema,
  captureSessionSchema,
  captureUploadPolicySchema,
  captureUploadTicketSchema,
  categoryPageSchema,
  placeClaimPageSchema,
  placeClaimSchema,
  placeHoursExceptionPageSchema,
  placeHoursExceptionSchema,
  placeBatchSchema,
  placePageSchema,
  placeSchema,
  placeWithDistancePageSchema,
  routeResponseSchema,
  searchResultsSchema,
  streetCoverageSchema,
  streetSceneManifestSchema,
  streetSceneReportSchema,
} from '@goway/contracts';
