/**
 * `@goway.to/sdk` — the canonical integration boundary for GoWay.
 *
 * Everything a consumer may rely on is exported from here, and nothing else is
 * part of the contract. Domain shapes, closed value sets and limits come from
 * GoWay's own `packages/contracts` — the zod schemas the API validates against
 * — so a consumer never imports a private GoWay package and never keeps its own
 * copy of `Place`. The schemas themselves are not exported: the types and the
 * values are the contract, and the SDK validates every request and parses every
 * response with them on the consumer's behalf.
 *
 * Nothing in this package knows which map renderer, geocoder or router GoWay is
 * running: MapLibre, OpenFreeMap, Photon, Nominatim and Valhalla are
 * replaceable adapters BEHIND these shapes. Installing this SDK pulls in no
 * renderer and no provider client; its one dependency is `zod`.
 */

export {
  createGoWayClient,
  DEFAULT_GOWAY_API_BASE_URL,
  DEFAULT_GOWAY_TIMEOUT_MS,
  DEFAULT_GOWAY_WEB_BASE_URL,
} from './client';
export type {
  GoWayCapturesApi,
  GoWayClaimsApi,
  GoWayClient,
  GoWayClientOptions,
  GoWayGeocodeApi,
  GoWayLinks,
  GoWayPlaceCapabilitiesApi,
  GoWayPlaceClaimsApi,
  GoWayPlaceReadOptions,
  GoWayPlacesApi,
  GoWayRequestOptions,
  GoWayRoutesApi,
  GoWaySearchApi,
  GoWayStreet3dApi,
  PlaceLinkTarget,
} from './client';

export { iterateGoWayPages } from './pagination';
export type { GoWayPageLike } from './pagination';

export {
  GoWayAbortError,
  GoWayApiError,
  GoWayConflictError,
  GoWayError,
  GoWayForbiddenError,
  GoWayGoneError,
  GoWayNetworkError,
  GoWayNoRouteError,
  GoWayNotFoundError,
  GoWayRateLimitError,
  GoWayResponseError,
  GoWayTimeoutError,
  GoWayUnauthorizedError,
  GoWayUnavailableError,
  GoWayUnknownRouteError,
  GoWayUnsupportedModeError,
  GoWayValidationError,
  isGoWayError,
} from './errors';
export type { GoWayErrorCode, GoWayErrorOptions, GoWayRateLimitErrorOptions } from './errors';

export type { GoWayAccessTokenGetter } from './transport';
export type {
  GoWayAbortSignal,
  GoWayFetch,
  GoWayFetchInit,
  GoWayFetchResponse,
  GoWayHeadersLike,
  GoWayHttpMethod,
} from './runtime';

export {
  // Places
  PLACE_STATUSES,
  WRITABLE_PLACE_STATUSES,
  PUBLISHED_PLACE_STATUSES,
  PLACE_VERIFICATION_STATES,
  CAPABILITY_VERIFICATIONS,
  WELL_KNOWN_CAPABILITIES,
  PLACE_CLAIM_ROLES,
  PLACE_CLAIM_STATES,
  MAX_PLACE_LIST_LIMIT,
  DEFAULT_PLACE_LIST_LIMIT,
  MAX_RADIUS_METERS,
  MAX_BOUNDS_SPAN_DEGREES,
  MAX_CLAIM_LIST_LIMIT,
  DEFAULT_CLAIM_LIST_LIMIT,
  capabilityValueHolds,
  placeDisplayName,
  placeHasCapability,
  splitCapabilityKey,
  strongestCapability,
  // Captures
  CAPTURE_ASSET_STATES,
  CAPTURE_CONTENT_HASH_ALGORITHM,
  CAPTURE_LOCATION_ORIGIN_RANK,
  CAPTURE_LOCATION_ORIGINS,
  CAPTURE_LOCATION_WITNESSES,
  CAPTURE_MEDIA_KINDS,
  CAPTURE_PRIVACY_STATES,
  CAPTURE_RETENTION_CLASSES,
  CAPTURE_SOURCES,
  DELETION_REASONS,
  RETENTION_CLASSES,
  RETENTION_REASONS,
  MAX_CAPTURE_LIST_LIMIT,
  DEFAULT_CAPTURE_LIST_LIMIT,
  // Street 3D
  STREET_COVERAGE_AREA_STATES,
  STREET_SCENE_ASSET_ROLES,
  STREET_SCENE_PROFILES,
  STREET_SCENE_REPORT_REASONS,
  // Search and directions
  SEARCH_RESULT_KINDS,
  SEARCH_SOURCES,
  SEARCH_MAX_LIMIT,
  SEARCH_MAX_DEPTH,
  MAX_SEARCH_QUERY_LENGTH,
  STRUCTURED_GEOCODE_FIELDS,
  TRAVEL_MODES,
  MANEUVER_TYPES,
  MAX_WAYPOINTS,
  // Geography, language, paging
  boundingBoxWidth,
  toGeoCoordinate,
  toGeoPosition,
  baseLanguageTag,
  normalizeLanguageTag,
  LANGUAGE_TAG_PATTERN,
  MAX_LANGUAGE_TAG_LENGTH,
  MAX_CURSOR_LENGTH,
  // Errors and the API root
  API_ERROR_CODES,
  API_ERROR_RETRYABLE,
  API_ERROR_STATUS,
  isApiErrorCode,
  GOWAY_API_BASE_PATH,
} from './contract';

export type {
  // Geography
  GeoBoundingBox,
  GeoCoordinate,
  GeoGeometry,
  GeoJsonLineString,
  GeoJsonMultiPolygon,
  GeoJsonPoint,
  GeoJsonPolygon,
  GeoPosition,
  MapViewport,
  Meters,
  Seconds,
  // Paging and errors
  Page,
  ApiErrorBody,
  ApiErrorCode,
  ApiErrorDetails,
  // Places
  CapabilityKey,
  CapabilityValue,
  CapabilityVerification,
  ClaimListQuery,
  NearbyPlacesQuery,
  OpeningHours,
  OpeningHoursInterval,
  Place,
  PlaceCapability,
  PlaceCapabilityAssertion,
  PlaceCapabilityInput,
  PlaceClaim,
  PlaceClaimInput,
  PlaceClaimPage,
  PlaceClaimRole,
  PlaceClaimState,
  PlaceContact,
  PlaceCreateInput,
  PlaceId,
  PlaceName,
  PlaceNameInput,
  PlacePage,
  PlaceReadQuery,
  PlacesInBoundsQuery,
  PlaceSourceRef,
  PlaceSourceRefInput,
  PlaceStatus,
  PlaceUpdateInput,
  PlaceVerification,
  PlaceVerificationState,
  PlaceWithDistance,
  PlaceWithDistancePage,
  StructuredAddress,
  WellKnownCapability,
  WritablePlaceStatus,
  // Captures
  CaptureAnchor,
  CaptureAsset,
  CaptureAssetId,
  CaptureAssetInput,
  CaptureAssetPage,
  CaptureAssetState,
  CaptureCameraMetadata,
  CaptureContentHashAlgorithm,
  CaptureListQuery,
  CaptureLocationEvidence,
  CaptureLocationEvidenceInput,
  CaptureLocationOrigin,
  CaptureLocationWitness,
  CaptureMediaKind,
  CaptureMediaObject,
  CapturePrivacyGate,
  CapturePrivacyState,
  CaptureRetentionClass,
  CaptureSession,
  CaptureSessionId,
  CaptureSessionInput,
  CaptureSessionPage,
  CaptureSource,
  CaptureUploadIntent,
  CaptureUploadPolicy,
  CaptureUploadTicket,
  DeletionReason,
  ExifGps,
  RetentionClass,
  RetentionReason,
  StoredObjectLifecycle,
  // Street 3D
  StreetCoverage,
  StreetCoverageArea,
  StreetCoverageAreaState,
  StreetCoverageQuery,
  StreetSceneAsset,
  StreetSceneAssetRole,
  StreetSceneFieldOfView,
  StreetSceneId,
  StreetSceneInitialView,
  StreetSceneManifest,
  StreetSceneNavigation,
  StreetSceneProfile,
  StreetSceneQuality,
  StreetSceneReport,
  StreetSceneReportInput,
  StreetSceneReportReason,
  StreetSceneSummary,
  StreetSceneViewpoint,
  StreetSceneWorldTransform,
  // Search
  ReverseGeocodeQuery,
  SearchQuery,
  SearchResult,
  SearchResultContext,
  SearchResultKind,
  SearchResults,
  SearchSource,
  StructuredGeocodeQuery,
  // Directions
  ManeuverType,
  Route,
  RouteLeg,
  RouteLocation,
  RouteManeuver,
  RouteRequest,
  RouteResponse,
  TravelMode,
} from './contract';
