-- oxy:deploy-phase=pre
-- Custom SQL migration: the category taxonomy as data, and what holds
-- `places.categories` to it once `0017` drops the static CHECK.
--
-- PRE, like `0015`: the previous image writes only keys of the registry this
-- seed is generated from, so every trigger below accepts everything it writes.
--
-- 1. The seed: the 148 categories of the 0.3.0 registry with their glyphs and
--    OpenStreetMap tags, and their labels in twelve languages (`en`, `ar`,
--    `bn`, `ca`, `de`, `es`, `fr`, `hi`, `ja`, `pt-BR`, `ru`, `zh-Hans`) —
--    1,776 rows, GENERATED from the registry and from the label translations
--    (`i18n/category-labels.json`, whose English and Spanish are the
--    registry's), nothing retyped. Positions are each category's place among
--    its siblings, in tens. The seed is a migration, not a moderator's write,
--    and records no `place_category_events`.
-- 2. English is required: a deferred constraint trigger refuses, at commit, a
--    category without an `en` label — whether the category arrived without one
--    or its `en` row was deleted or moved to another language.
-- 3. Keys are immutable, and a key a place carries is never deleted.
-- 4. `places.categories` holds active categories: an INSERT, or an UPDATE that
--    ADDS a key, is refused unless every added key is an `active` category. A
--    key the row already carried may stay (a deprecated category never makes a
--    place uneditable) and existing rows are never re-checked: what `0013`'s
--    CHECK validated stays valid, and a deprecated key stays readable.
--
-- Lock order: everything up to (4) touches only the new tables. (4) takes
-- SHARE ROW EXCLUSIVE on `places` (writes wait, reads do not) and `0017`
-- ACCESS EXCLUSIVE (everything waits) for milliseconds, until the phase
-- commits. `lock_timeout` makes a long-running statement on `places` fail this
-- phase instead of queueing every read behind it; the deploy is then re-run.
-- It is `SET LOCAL`, so it lasts for the phase's one transaction — `0017`
-- included — and no longer.
INSERT INTO "place_categories" ("key", "parent_key", "icon", "position") VALUES
  ('food', NULL, 'restaurant', 0),
  ('food.restaurant', 'food', 'restaurant', 0),
  ('food.fast_food', 'food', 'restaurant', 10),
  ('food.cafe', 'food', 'cafe', 20),
  ('food.bar', 'food', 'bar', 30),
  ('food.pub', 'food', 'bar', 40),
  ('food.nightclub', 'food', 'nightlife', 50),
  ('food.ice_cream', 'food', 'cafe', 60),
  ('food.bakery', 'food', 'bakery', 70),
  ('food.confectionery', 'food', 'bakery', 80),
  ('shop', NULL, 'shop', 10),
  ('shop.supermarket', 'shop', 'grocery', 0),
  ('shop.convenience', 'shop', 'grocery', 10),
  ('shop.greengrocer', 'shop', 'grocery', 20),
  ('shop.butcher', 'shop', 'grocery', 30),
  ('shop.deli', 'shop', 'grocery', 40),
  ('shop.marketplace', 'shop', 'grocery', 50),
  ('shop.alcohol', 'shop', 'bar', 60),
  ('shop.books', 'shop', 'book', 70),
  ('shop.clothes', 'shop', 'clothing', 80),
  ('shop.shoes', 'shop', 'clothing', 90),
  ('shop.jewelry', 'shop', 'gift', 100),
  ('shop.gift', 'shop', 'gift', 110),
  ('shop.florist', 'shop', 'nature', 120),
  ('shop.hardware', 'shop', 'hardware', 130),
  ('shop.furniture', 'shop', 'shop', 140),
  ('shop.electronics', 'shop', 'electronics', 150),
  ('shop.beauty', 'shop', 'beauty', 160),
  ('shop.hairdresser', 'shop', 'beauty', 170),
  ('shop.optician', 'shop', 'shop', 180),
  ('shop.chemist', 'shop', 'pharmacy', 190),
  ('shop.department_store', 'shop', 'shop', 200),
  ('shop.sports', 'shop', 'sport', 210),
  ('shop.bicycle', 'shop', 'bike', 220),
  ('shop.music', 'shop', 'music', 230),
  ('shop.toys', 'shop', 'gift', 240),
  ('shop.stationery', 'shop', 'book', 250),
  ('shop.newsagent', 'shop', 'book', 260),
  ('shop.tobacco', 'shop', 'shop', 270),
  ('shop.pet', 'shop', 'pet', 280),
  ('shop.laundry', 'shop', 'laundry', 290),
  ('shop.second_hand', 'shop', 'shop', 300),
  ('shop.art', 'shop', 'art', 310),
  ('shop.travel_agency', 'shop', 'shop', 320),
  ('lodging', NULL, 'hotel', 20),
  ('lodging.hotel', 'lodging', 'hotel', 0),
  ('lodging.hostel', 'lodging', 'hotel', 10),
  ('lodging.guest_house', 'lodging', 'hotel', 20),
  ('lodging.apartment', 'lodging', 'hotel', 30),
  ('lodging.camping', 'lodging', 'camping', 40),
  ('lodging.hut', 'lodging', 'camping', 50),
  ('leisure', NULL, 'park', 30),
  ('leisure.park', 'leisure', 'park', 0),
  ('leisure.garden', 'leisure', 'nature', 10),
  ('leisure.playground', 'leisure', 'park', 20),
  ('leisure.dog_park', 'leisure', 'pet', 30),
  ('leisure.picnic_site', 'leisure', 'park', 40),
  ('leisure.nature_reserve', 'leisure', 'nature', 50),
  ('leisure.beach', 'leisure', 'water', 60),
  ('leisure.marina', 'leisure', 'ferry', 70),
  ('leisure.water', 'leisure', 'water', 80),
  ('leisure.amusement', 'leisure', 'entertainment', 90),
  ('leisure.fitness', 'leisure', 'sport', 100),
  ('sport', NULL, 'sport', 40),
  ('sport.centre', 'sport', 'sport', 0),
  ('sport.pitch', 'sport', 'sport', 10),
  ('sport.stadium', 'sport', 'sport', 20),
  ('sport.swimming', 'sport', 'water', 30),
  ('sport.golf', 'sport', 'golf', 40),
  ('sport.ice_rink', 'sport', 'sport', 50),
  ('sport.horse_riding', 'sport', 'sport', 60),
  ('sport.climbing', 'sport', 'sport', 70),
  ('sport.skiing', 'sport', 'sport', 80),
  ('culture', NULL, 'museum', 50),
  ('culture.museum', 'culture', 'museum', 0),
  ('culture.gallery', 'culture', 'art', 10),
  ('culture.theatre', 'culture', 'theatre', 20),
  ('culture.cinema', 'culture', 'cinema', 30),
  ('culture.music_venue', 'culture', 'music', 40),
  ('culture.attraction', 'culture', 'landmark', 50),
  ('culture.viewpoint', 'culture', 'landmark', 60),
  ('culture.artwork', 'culture', 'art', 70),
  ('culture.zoo', 'culture', 'pet', 80),
  ('culture.aquarium', 'culture', 'water', 90),
  ('culture.information', 'culture', 'information', 100),
  ('culture.historic', 'culture', 'landmark', 110),
  ('culture.monument', 'culture', 'landmark', 120),
  ('culture.castle', 'culture', 'landmark', 130),
  ('culture.archaeological_site', 'culture', 'landmark', 140),
  ('transport', NULL, 'subway', 60),
  ('transport.bus_stop', 'transport', 'bus', 0),
  ('transport.bus_station', 'transport', 'bus', 10),
  ('transport.rail_station', 'transport', 'train', 20),
  ('transport.tram_stop', 'transport', 'train', 30),
  ('transport.aerialway', 'transport', 'subway', 40),
  ('transport.ferry_terminal', 'transport', 'ferry', 50),
  ('transport.taxi', 'transport', 'car', 60),
  ('transport.bicycle_rental', 'transport', 'bike', 70),
  ('transport.car_rental', 'transport', 'car', 80),
  ('vehicle', NULL, 'car', 70),
  ('vehicle.fuel', 'vehicle', 'fuel', 0),
  ('vehicle.charging', 'vehicle', 'charging', 10),
  ('vehicle.parking', 'vehicle', 'parking', 20),
  ('vehicle.repair', 'vehicle', 'tools', 30),
  ('vehicle.dealer', 'vehicle', 'car', 40),
  ('vehicle.car_wash', 'vehicle', 'car', 50),
  ('vehicle.motorcycle', 'vehicle', 'car', 60),
  ('health', NULL, 'health', 80),
  ('health.hospital', 'health', 'hospital', 0),
  ('health.clinic', 'health', 'health', 10),
  ('health.doctor', 'health', 'health', 20),
  ('health.dentist', 'health', 'health', 30),
  ('health.pharmacy', 'health', 'pharmacy', 40),
  ('health.veterinary', 'health', 'pet', 50),
  ('health.care_home', 'health', 'health', 60),
  ('education', NULL, 'school', 90),
  ('education.school', 'education', 'school', 0),
  ('education.kindergarten', 'education', 'school', 10),
  ('education.university', 'education', 'school', 20),
  ('education.library', 'education', 'book', 30),
  ('education.training', 'education', 'school', 40),
  ('civic', NULL, 'civic', 100),
  ('civic.townhall', 'civic', 'civic', 0),
  ('civic.courthouse', 'civic', 'civic', 10),
  ('civic.police', 'civic', 'police', 20),
  ('civic.fire_station', 'civic', 'civic', 30),
  ('civic.post_office', 'civic', 'mail', 40),
  ('civic.post_box', 'civic', 'mail', 50),
  ('civic.community_centre', 'civic', 'civic', 60),
  ('civic.embassy', 'civic', 'civic', 70),
  ('civic.toilets', 'civic', 'toilets', 80),
  ('civic.cemetery', 'civic', 'landmark', 90),
  ('finance', NULL, 'bank', 110),
  ('finance.bank', 'finance', 'bank', 0),
  ('finance.atm', 'finance', 'bank', 10),
  ('finance.exchange', 'finance', 'bank', 20),
  ('worship', NULL, 'worship', 120),
  ('services', NULL, 'tools', 130),
  ('office', NULL, 'office', 140),
  ('office.coworking', 'office', 'office', 0),
  ('office.company', 'office', 'office', 10),
  ('office.government', 'office', 'civic', 20),
  ('office.estate_agent', 'office', 'office', 30),
  ('office.lawyer', 'office', 'office', 40),
  ('office.insurance', 'office', 'office', 50),
  ('craft', NULL, 'tools', 150),
  ('craft.brewery', 'craft', 'bar', 0),
  ('craft.winery', 'craft', 'bar', 10);
--> statement-breakpoint
INSERT INTO "place_category_labels" ("category_key", "language", "label") VALUES
  ('food', 'en', 'Food & drink'),
  ('food', 'ar', 'طعام ومشروبات'),
  ('food', 'bn', 'খাবার ও পানীয়'),
  ('food', 'ca', 'Menjar i beure'),
  ('food', 'de', 'Essen & Trinken'),
  ('food', 'es', 'Comida y bebida'),
  ('food', 'fr', 'Boire et manger'),
  ('food', 'hi', 'खाना-पीना'),
  ('food', 'ja', '飲食'),
  ('food', 'pt-BR', 'Comida e bebida'),
  ('food', 'ru', 'Еда и напитки'),
  ('food', 'zh-Hans', '餐饮'),
  ('food.restaurant', 'en', 'Restaurant'),
  ('food.restaurant', 'ar', 'مطعم'),
  ('food.restaurant', 'bn', 'রেস্তোরাঁ'),
  ('food.restaurant', 'ca', 'Restaurant'),
  ('food.restaurant', 'de', 'Restaurant'),
  ('food.restaurant', 'es', 'Restaurante'),
  ('food.restaurant', 'fr', 'Restaurant'),
  ('food.restaurant', 'hi', 'रेस्टोरेंट'),
  ('food.restaurant', 'ja', 'レストラン'),
  ('food.restaurant', 'pt-BR', 'Restaurante'),
  ('food.restaurant', 'ru', 'Ресторан'),
  ('food.restaurant', 'zh-Hans', '餐厅'),
  ('food.fast_food', 'en', 'Fast food'),
  ('food.fast_food', 'ar', 'وجبات سريعة'),
  ('food.fast_food', 'bn', 'ফাস্ট ফুড'),
  ('food.fast_food', 'ca', 'Menjar ràpid'),
  ('food.fast_food', 'de', 'Fast Food'),
  ('food.fast_food', 'es', 'Comida rápida'),
  ('food.fast_food', 'fr', 'Restauration rapide'),
  ('food.fast_food', 'hi', 'फ़ास्ट फ़ूड'),
  ('food.fast_food', 'ja', 'ファストフード'),
  ('food.fast_food', 'pt-BR', 'Fast food'),
  ('food.fast_food', 'ru', 'Фастфуд'),
  ('food.fast_food', 'zh-Hans', '快餐'),
  ('food.cafe', 'en', 'Café'),
  ('food.cafe', 'ar', 'مقهى'),
  ('food.cafe', 'bn', 'ক্যাফে'),
  ('food.cafe', 'ca', 'Cafeteria'),
  ('food.cafe', 'de', 'Café'),
  ('food.cafe', 'es', 'Cafetería'),
  ('food.cafe', 'fr', 'Café'),
  ('food.cafe', 'hi', 'कैफ़े'),
  ('food.cafe', 'ja', 'カフェ'),
  ('food.cafe', 'pt-BR', 'Cafeteria'),
  ('food.cafe', 'ru', 'Кафе'),
  ('food.cafe', 'zh-Hans', '咖啡馆'),
  ('food.bar', 'en', 'Bar'),
  ('food.bar', 'ar', 'بار'),
  ('food.bar', 'bn', 'বার'),
  ('food.bar', 'ca', 'Bar'),
  ('food.bar', 'de', 'Bar'),
  ('food.bar', 'es', 'Bar'),
  ('food.bar', 'fr', 'Bar'),
  ('food.bar', 'hi', 'बार'),
  ('food.bar', 'ja', 'バー'),
  ('food.bar', 'pt-BR', 'Bar'),
  ('food.bar', 'ru', 'Бар'),
  ('food.bar', 'zh-Hans', '酒吧'),
  ('food.pub', 'en', 'Pub'),
  ('food.pub', 'ar', 'حانة'),
  ('food.pub', 'bn', 'পাব'),
  ('food.pub', 'ca', 'Pub'),
  ('food.pub', 'de', 'Kneipe'),
  ('food.pub', 'es', 'Pub'),
  ('food.pub', 'fr', 'Pub'),
  ('food.pub', 'hi', 'पब'),
  ('food.pub', 'ja', 'パブ'),
  ('food.pub', 'pt-BR', 'Pub'),
  ('food.pub', 'ru', 'Паб'),
  ('food.pub', 'zh-Hans', '酒馆'),
  ('food.nightclub', 'en', 'Nightclub'),
  ('food.nightclub', 'ar', 'ملهى ليلي'),
  ('food.nightclub', 'bn', 'নাইটক্লাব'),
  ('food.nightclub', 'ca', 'Discoteca'),
  ('food.nightclub', 'de', 'Nachtclub'),
  ('food.nightclub', 'es', 'Discoteca'),
  ('food.nightclub', 'fr', 'Boîte de nuit'),
  ('food.nightclub', 'hi', 'नाइटक्लब'),
  ('food.nightclub', 'ja', 'ナイトクラブ'),
  ('food.nightclub', 'pt-BR', 'Balada'),
  ('food.nightclub', 'ru', 'Ночной клуб'),
  ('food.nightclub', 'zh-Hans', '夜店'),
  ('food.ice_cream', 'en', 'Ice cream'),
  ('food.ice_cream', 'ar', 'محل آيس كريم'),
  ('food.ice_cream', 'bn', 'আইসক্রিম'),
  ('food.ice_cream', 'ca', 'Gelateria'),
  ('food.ice_cream', 'de', 'Eisdiele'),
  ('food.ice_cream', 'es', 'Heladería'),
  ('food.ice_cream', 'fr', 'Glacier'),
  ('food.ice_cream', 'hi', 'आइसक्रीम'),
  ('food.ice_cream', 'ja', 'アイスクリーム'),
  ('food.ice_cream', 'pt-BR', 'Sorveteria'),
  ('food.ice_cream', 'ru', 'Мороженое'),
  ('food.ice_cream', 'zh-Hans', '冰淇淋'),
  ('food.bakery', 'en', 'Bakery'),
  ('food.bakery', 'ar', 'مخبز'),
  ('food.bakery', 'bn', 'বেকারি'),
  ('food.bakery', 'ca', 'Forn de pa'),
  ('food.bakery', 'de', 'Bäckerei'),
  ('food.bakery', 'es', 'Panadería'),
  ('food.bakery', 'fr', 'Boulangerie'),
  ('food.bakery', 'hi', 'बेकरी'),
  ('food.bakery', 'ja', 'パン屋'),
  ('food.bakery', 'pt-BR', 'Padaria'),
  ('food.bakery', 'ru', 'Пекарня'),
  ('food.bakery', 'zh-Hans', '面包店'),
  ('food.confectionery', 'en', 'Sweets'),
  ('food.confectionery', 'ar', 'حلويات'),
  ('food.confectionery', 'bn', 'মিষ্টির দোকান'),
  ('food.confectionery', 'ca', 'Llaminadures'),
  ('food.confectionery', 'de', 'Süßwaren'),
  ('food.confectionery', 'es', 'Dulcería'),
  ('food.confectionery', 'fr', 'Confiserie'),
  ('food.confectionery', 'hi', 'मिठाई की दुकान'),
  ('food.confectionery', 'ja', '菓子店'),
  ('food.confectionery', 'pt-BR', 'Doceria'),
  ('food.confectionery', 'ru', 'Сладости'),
  ('food.confectionery', 'zh-Hans', '糖果店'),
  ('shop', 'en', 'Shops'),
  ('shop', 'ar', 'متاجر'),
  ('shop', 'bn', 'দোকান'),
  ('shop', 'ca', 'Botigues'),
  ('shop', 'de', 'Geschäfte'),
  ('shop', 'es', 'Tiendas'),
  ('shop', 'fr', 'Commerces'),
  ('shop', 'hi', 'दुकानें'),
  ('shop', 'ja', 'ショップ'),
  ('shop', 'pt-BR', 'Lojas'),
  ('shop', 'ru', 'Магазины'),
  ('shop', 'zh-Hans', '购物'),
  ('shop.supermarket', 'en', 'Supermarket'),
  ('shop.supermarket', 'ar', 'سوبر ماركت'),
  ('shop.supermarket', 'bn', 'সুপারমার্কেট'),
  ('shop.supermarket', 'ca', 'Supermercat'),
  ('shop.supermarket', 'de', 'Supermarkt'),
  ('shop.supermarket', 'es', 'Supermercado'),
  ('shop.supermarket', 'fr', 'Supermarché'),
  ('shop.supermarket', 'hi', 'सुपरमार्केट'),
  ('shop.supermarket', 'ja', 'スーパー'),
  ('shop.supermarket', 'pt-BR', 'Supermercado'),
  ('shop.supermarket', 'ru', 'Супермаркет'),
  ('shop.supermarket', 'zh-Hans', '超市'),
  ('shop.convenience', 'en', 'Convenience store'),
  ('shop.convenience', 'ar', 'بقالة'),
  ('shop.convenience', 'bn', 'মুদির দোকান'),
  ('shop.convenience', 'ca', 'Botiga de queviures'),
  ('shop.convenience', 'de', 'Minimarkt'),
  ('shop.convenience', 'es', 'Tienda de conveniencia'),
  ('shop.convenience', 'fr', 'Supérette'),
  ('shop.convenience', 'hi', 'किराना स्टोर'),
  ('shop.convenience', 'ja', 'コンビニ'),
  ('shop.convenience', 'pt-BR', 'Loja de conveniência'),
  ('shop.convenience', 'ru', 'Магазин у дома'),
  ('shop.convenience', 'zh-Hans', '便利店'),
  ('shop.greengrocer', 'en', 'Greengrocer'),
  ('shop.greengrocer', 'ar', 'خضار وفواكه'),
  ('shop.greengrocer', 'bn', 'ফল ও সবজির দোকান'),
  ('shop.greengrocer', 'ca', 'Fruiteria'),
  ('shop.greengrocer', 'de', 'Obst & Gemüse'),
  ('shop.greengrocer', 'es', 'Frutería'),
  ('shop.greengrocer', 'fr', 'Primeur'),
  ('shop.greengrocer', 'hi', 'फल-सब्ज़ी की दुकान'),
  ('shop.greengrocer', 'ja', '青果店'),
  ('shop.greengrocer', 'pt-BR', 'Hortifrúti'),
  ('shop.greengrocer', 'ru', 'Овощи и фрукты'),
  ('shop.greengrocer', 'zh-Hans', '果蔬店'),
  ('shop.butcher', 'en', 'Butcher'),
  ('shop.butcher', 'ar', 'جزار'),
  ('shop.butcher', 'bn', 'মাংসের দোকান'),
  ('shop.butcher', 'ca', 'Carnisseria'),
  ('shop.butcher', 'de', 'Metzgerei'),
  ('shop.butcher', 'es', 'Carnicería'),
  ('shop.butcher', 'fr', 'Boucherie'),
  ('shop.butcher', 'hi', 'मीट की दुकान'),
  ('shop.butcher', 'ja', '精肉店'),
  ('shop.butcher', 'pt-BR', 'Açougue'),
  ('shop.butcher', 'ru', 'Мясная лавка'),
  ('shop.butcher', 'zh-Hans', '肉店'),
  ('shop.deli', 'en', 'Delicatessen'),
  ('shop.deli', 'ar', 'أطعمة راقية'),
  ('shop.deli', 'bn', 'ডেলি'),
  ('shop.deli', 'ca', 'Xarcuteria'),
  ('shop.deli', 'de', 'Feinkost'),
  ('shop.deli', 'es', 'Charcutería'),
  ('shop.deli', 'fr', 'Épicerie fine'),
  ('shop.deli', 'hi', 'डेली'),
  ('shop.deli', 'ja', 'デリカテッセン'),
  ('shop.deli', 'pt-BR', 'Empório'),
  ('shop.deli', 'ru', 'Деликатесы'),
  ('shop.deli', 'zh-Hans', '熟食店'),
  ('shop.marketplace', 'en', 'Market'),
  ('shop.marketplace', 'ar', 'سوق'),
  ('shop.marketplace', 'bn', 'বাজার'),
  ('shop.marketplace', 'ca', 'Mercat'),
  ('shop.marketplace', 'de', 'Markt'),
  ('shop.marketplace', 'es', 'Mercado'),
  ('shop.marketplace', 'fr', 'Marché'),
  ('shop.marketplace', 'hi', 'बाज़ार'),
  ('shop.marketplace', 'ja', '市場'),
  ('shop.marketplace', 'pt-BR', 'Mercado'),
  ('shop.marketplace', 'ru', 'Рынок'),
  ('shop.marketplace', 'zh-Hans', '市场'),
  ('shop.alcohol', 'en', 'Wine & spirits'),
  ('shop.alcohol', 'ar', 'نبيذ ومشروبات روحية'),
  ('shop.alcohol', 'bn', 'মদের দোকান'),
  ('shop.alcohol', 'ca', 'Vins i licors'),
  ('shop.alcohol', 'de', 'Wein & Spirituosen'),
  ('shop.alcohol', 'es', 'Vinos y licores'),
  ('shop.alcohol', 'fr', 'Vins et spiritueux'),
  ('shop.alcohol', 'hi', 'शराब की दुकान'),
  ('shop.alcohol', 'ja', '酒屋'),
  ('shop.alcohol', 'pt-BR', 'Vinhos e destilados'),
  ('shop.alcohol', 'ru', 'Вино и крепкие напитки'),
  ('shop.alcohol', 'zh-Hans', '酒类专卖'),
  ('shop.books', 'en', 'Bookshop'),
  ('shop.books', 'ar', 'متجر كتب'),
  ('shop.books', 'bn', 'বইয়ের দোকান'),
  ('shop.books', 'ca', 'Llibreria'),
  ('shop.books', 'de', 'Buchhandlung'),
  ('shop.books', 'es', 'Librería'),
  ('shop.books', 'fr', 'Librairie'),
  ('shop.books', 'hi', 'किताबों की दुकान'),
  ('shop.books', 'ja', '書店'),
  ('shop.books', 'pt-BR', 'Livraria'),
  ('shop.books', 'ru', 'Книжный магазин'),
  ('shop.books', 'zh-Hans', '书店'),
  ('shop.clothes', 'en', 'Clothes'),
  ('shop.clothes', 'ar', 'ملابس'),
  ('shop.clothes', 'bn', 'পোশাক'),
  ('shop.clothes', 'ca', 'Roba'),
  ('shop.clothes', 'de', 'Kleidung'),
  ('shop.clothes', 'es', 'Ropa'),
  ('shop.clothes', 'fr', 'Vêtements'),
  ('shop.clothes', 'hi', 'कपड़े'),
  ('shop.clothes', 'ja', '衣料品店'),
  ('shop.clothes', 'pt-BR', 'Roupas'),
  ('shop.clothes', 'ru', 'Одежда'),
  ('shop.clothes', 'zh-Hans', '服装'),
  ('shop.shoes', 'en', 'Shoes'),
  ('shop.shoes', 'ar', 'أحذية'),
  ('shop.shoes', 'bn', 'জুতো'),
  ('shop.shoes', 'ca', 'Sabateria'),
  ('shop.shoes', 'de', 'Schuhe'),
  ('shop.shoes', 'es', 'Zapatería'),
  ('shop.shoes', 'fr', 'Chaussures'),
  ('shop.shoes', 'hi', 'जूते'),
  ('shop.shoes', 'ja', '靴店'),
  ('shop.shoes', 'pt-BR', 'Sapataria'),
  ('shop.shoes', 'ru', 'Обувь'),
  ('shop.shoes', 'zh-Hans', '鞋店'),
  ('shop.jewelry', 'en', 'Jewellery'),
  ('shop.jewelry', 'ar', 'مجوهرات'),
  ('shop.jewelry', 'bn', 'গয়না'),
  ('shop.jewelry', 'ca', 'Joieria'),
  ('shop.jewelry', 'de', 'Schmuck'),
  ('shop.jewelry', 'es', 'Joyería'),
  ('shop.jewelry', 'fr', 'Bijouterie'),
  ('shop.jewelry', 'hi', 'ज्वेलरी'),
  ('shop.jewelry', 'ja', 'ジュエリー'),
  ('shop.jewelry', 'pt-BR', 'Joalheria'),
  ('shop.jewelry', 'ru', 'Ювелирный магазин'),
  ('shop.jewelry', 'zh-Hans', '珠宝'),
  ('shop.gift', 'en', 'Gifts & souvenirs'),
  ('shop.gift', 'ar', 'هدايا وتذكارات'),
  ('shop.gift', 'bn', 'উপহার ও স্মারক'),
  ('shop.gift', 'ca', 'Regals i records'),
  ('shop.gift', 'de', 'Geschenke & Souvenirs'),
  ('shop.gift', 'es', 'Regalos y recuerdos'),
  ('shop.gift', 'fr', 'Cadeaux et souvenirs'),
  ('shop.gift', 'hi', 'गिफ़्ट और सुवेनियर'),
  ('shop.gift', 'ja', 'ギフト・お土産'),
  ('shop.gift', 'pt-BR', 'Presentes e lembranças'),
  ('shop.gift', 'ru', 'Подарки и сувениры'),
  ('shop.gift', 'zh-Hans', '礼品纪念品'),
  ('shop.florist', 'en', 'Florist'),
  ('shop.florist', 'ar', 'محل زهور'),
  ('shop.florist', 'bn', 'ফুলের দোকান'),
  ('shop.florist', 'ca', 'Floristeria'),
  ('shop.florist', 'de', 'Blumenladen'),
  ('shop.florist', 'es', 'Floristería'),
  ('shop.florist', 'fr', 'Fleuriste'),
  ('shop.florist', 'hi', 'फूलों की दुकान'),
  ('shop.florist', 'ja', '花屋'),
  ('shop.florist', 'pt-BR', 'Floricultura'),
  ('shop.florist', 'ru', 'Цветы'),
  ('shop.florist', 'zh-Hans', '花店'),
  ('shop.hardware', 'en', 'Hardware'),
  ('shop.hardware', 'ar', 'خردوات'),
  ('shop.hardware', 'bn', 'হার্ডওয়্যার'),
  ('shop.hardware', 'ca', 'Ferreteria'),
  ('shop.hardware', 'de', 'Baumarkt'),
  ('shop.hardware', 'es', 'Ferretería'),
  ('shop.hardware', 'fr', 'Quincaillerie'),
  ('shop.hardware', 'hi', 'हार्डवेयर'),
  ('shop.hardware', 'ja', 'ホームセンター'),
  ('shop.hardware', 'pt-BR', 'Loja de ferragens'),
  ('shop.hardware', 'ru', 'Хозтовары'),
  ('shop.hardware', 'zh-Hans', '五金建材'),
  ('shop.furniture', 'en', 'Home & furniture'),
  ('shop.furniture', 'ar', 'منزل وأثاث'),
  ('shop.furniture', 'bn', 'গৃহসজ্জা ও আসবাব'),
  ('shop.furniture', 'ca', 'Llar i mobles'),
  ('shop.furniture', 'de', 'Wohnen & Möbel'),
  ('shop.furniture', 'es', 'Hogar y muebles'),
  ('shop.furniture', 'fr', 'Maison et ameublement'),
  ('shop.furniture', 'hi', 'होम और फ़र्नीचर'),
  ('shop.furniture', 'ja', '家具・インテリア'),
  ('shop.furniture', 'pt-BR', 'Casa e móveis'),
  ('shop.furniture', 'ru', 'Дом и мебель'),
  ('shop.furniture', 'zh-Hans', '家居家具'),
  ('shop.electronics', 'en', 'Electronics'),
  ('shop.electronics', 'ar', 'إلكترونيات'),
  ('shop.electronics', 'bn', 'ইলেকট্রনিক্স'),
  ('shop.electronics', 'ca', 'Electrònica'),
  ('shop.electronics', 'de', 'Elektronik'),
  ('shop.electronics', 'es', 'Electrónica'),
  ('shop.electronics', 'fr', 'Électronique'),
  ('shop.electronics', 'hi', 'इलेक्ट्रॉनिक्स'),
  ('shop.electronics', 'ja', '家電'),
  ('shop.electronics', 'pt-BR', 'Eletrônicos'),
  ('shop.electronics', 'ru', 'Электроника'),
  ('shop.electronics', 'zh-Hans', '数码电器'),
  ('shop.beauty', 'en', 'Beauty'),
  ('shop.beauty', 'ar', 'تجميل'),
  ('shop.beauty', 'bn', 'বিউটি'),
  ('shop.beauty', 'ca', 'Bellesa'),
  ('shop.beauty', 'de', 'Kosmetik'),
  ('shop.beauty', 'es', 'Belleza'),
  ('shop.beauty', 'fr', 'Beauté'),
  ('shop.beauty', 'hi', 'ब्यूटी'),
  ('shop.beauty', 'ja', 'コスメ・美容'),
  ('shop.beauty', 'pt-BR', 'Beleza'),
  ('shop.beauty', 'ru', 'Красота'),
  ('shop.beauty', 'zh-Hans', '美妆'),
  ('shop.hairdresser', 'en', 'Hairdresser'),
  ('shop.hairdresser', 'ar', 'تصفيف الشعر'),
  ('shop.hairdresser', 'bn', 'সেলুন'),
  ('shop.hairdresser', 'ca', 'Perruqueria'),
  ('shop.hairdresser', 'de', 'Friseur'),
  ('shop.hairdresser', 'es', 'Peluquería'),
  ('shop.hairdresser', 'fr', 'Coiffeur'),
  ('shop.hairdresser', 'hi', 'सैलून'),
  ('shop.hairdresser', 'ja', '美容院・理容室'),
  ('shop.hairdresser', 'pt-BR', 'Cabeleireiro'),
  ('shop.hairdresser', 'ru', 'Парикмахерская'),
  ('shop.hairdresser', 'zh-Hans', '美发'),
  ('shop.optician', 'en', 'Optician'),
  ('shop.optician', 'ar', 'بصريات'),
  ('shop.optician', 'bn', 'চশমার দোকান'),
  ('shop.optician', 'ca', 'Òptica'),
  ('shop.optician', 'de', 'Optiker'),
  ('shop.optician', 'es', 'Óptica'),
  ('shop.optician', 'fr', 'Opticien'),
  ('shop.optician', 'hi', 'चश्मे की दुकान'),
  ('shop.optician', 'ja', '眼鏡店'),
  ('shop.optician', 'pt-BR', 'Ótica'),
  ('shop.optician', 'ru', 'Оптика'),
  ('shop.optician', 'zh-Hans', '眼镜店'),
  ('shop.chemist', 'en', 'Drugstore'),
  ('shop.chemist', 'ar', 'متجر مستحضرات'),
  ('shop.chemist', 'bn', 'ড্রাগস্টোর'),
  ('shop.chemist', 'ca', 'Drogueria'),
  ('shop.chemist', 'de', 'Drogerie'),
  ('shop.chemist', 'es', 'Droguería'),
  ('shop.chemist', 'fr', 'Droguerie'),
  ('shop.chemist', 'hi', 'ड्रगस्टोर'),
  ('shop.chemist', 'ja', 'ドラッグストア'),
  ('shop.chemist', 'pt-BR', 'Drogaria'),
  ('shop.chemist', 'ru', 'Бытовая химия'),
  ('shop.chemist', 'zh-Hans', '日化店'),
  ('shop.department_store', 'en', 'Department store'),
  ('shop.department_store', 'ar', 'متجر متعدد الأقسام'),
  ('shop.department_store', 'bn', 'ডিপার্টমেন্ট স্টোর'),
  ('shop.department_store', 'ca', 'Grans magatzems'),
  ('shop.department_store', 'de', 'Kaufhaus'),
  ('shop.department_store', 'es', 'Grandes almacenes'),
  ('shop.department_store', 'fr', 'Grand magasin'),
  ('shop.department_store', 'hi', 'डिपार्टमेंट स्टोर'),
  ('shop.department_store', 'ja', 'デパート'),
  ('shop.department_store', 'pt-BR', 'Loja de departamentos'),
  ('shop.department_store', 'ru', 'Универмаг'),
  ('shop.department_store', 'zh-Hans', '百货商场'),
  ('shop.sports', 'en', 'Sports shop'),
  ('shop.sports', 'ar', 'متجر رياضي'),
  ('shop.sports', 'bn', 'খেলার সামগ্রীর দোকান'),
  ('shop.sports', 'ca', 'Botiga d''esports'),
  ('shop.sports', 'de', 'Sportgeschäft'),
  ('shop.sports', 'es', 'Tienda de deportes'),
  ('shop.sports', 'fr', 'Magasin de sport'),
  ('shop.sports', 'hi', 'स्पोर्ट्स की दुकान'),
  ('shop.sports', 'ja', 'スポーツ用品店'),
  ('shop.sports', 'pt-BR', 'Loja de esportes'),
  ('shop.sports', 'ru', 'Спорттовары'),
  ('shop.sports', 'zh-Hans', '体育用品'),
  ('shop.bicycle', 'en', 'Bicycle shop'),
  ('shop.bicycle', 'ar', 'متجر دراجات'),
  ('shop.bicycle', 'bn', 'সাইকেলের দোকান'),
  ('shop.bicycle', 'ca', 'Botiga de bicicletes'),
  ('shop.bicycle', 'de', 'Fahrradladen'),
  ('shop.bicycle', 'es', 'Tienda de bicicletas'),
  ('shop.bicycle', 'fr', 'Magasin de vélos'),
  ('shop.bicycle', 'hi', 'साइकिल की दुकान'),
  ('shop.bicycle', 'ja', '自転車店'),
  ('shop.bicycle', 'pt-BR', 'Loja de bicicletas'),
  ('shop.bicycle', 'ru', 'Веломагазин'),
  ('shop.bicycle', 'zh-Hans', '自行车店'),
  ('shop.music', 'en', 'Music shop'),
  ('shop.music', 'ar', 'متجر موسيقى'),
  ('shop.music', 'bn', 'মিউজিকের দোকান'),
  ('shop.music', 'ca', 'Botiga de música'),
  ('shop.music', 'de', 'Musikgeschäft'),
  ('shop.music', 'es', 'Tienda de música'),
  ('shop.music', 'fr', 'Magasin de musique'),
  ('shop.music', 'hi', 'म्यूज़िक की दुकान'),
  ('shop.music', 'ja', '楽器店'),
  ('shop.music', 'pt-BR', 'Loja de música'),
  ('shop.music', 'ru', 'Музыкальный магазин'),
  ('shop.music', 'zh-Hans', '乐器店'),
  ('shop.toys', 'en', 'Toys'),
  ('shop.toys', 'ar', 'ألعاب'),
  ('shop.toys', 'bn', 'খেলনা'),
  ('shop.toys', 'ca', 'Joguineria'),
  ('shop.toys', 'de', 'Spielwaren'),
  ('shop.toys', 'es', 'Juguetería'),
  ('shop.toys', 'fr', 'Jouets'),
  ('shop.toys', 'hi', 'खिलौने'),
  ('shop.toys', 'ja', 'おもちゃ'),
  ('shop.toys', 'pt-BR', 'Loja de brinquedos'),
  ('shop.toys', 'ru', 'Игрушки'),
  ('shop.toys', 'zh-Hans', '玩具店'),
  ('shop.stationery', 'en', 'Stationery'),
  ('shop.stationery', 'ar', 'قرطاسية'),
  ('shop.stationery', 'bn', 'স্টেশনারি'),
  ('shop.stationery', 'ca', 'Papereria'),
  ('shop.stationery', 'de', 'Schreibwaren'),
  ('shop.stationery', 'es', 'Papelería'),
  ('shop.stationery', 'fr', 'Papeterie'),
  ('shop.stationery', 'hi', 'स्टेशनरी'),
  ('shop.stationery', 'ja', '文房具店'),
  ('shop.stationery', 'pt-BR', 'Papelaria'),
  ('shop.stationery', 'ru', 'Канцтовары'),
  ('shop.stationery', 'zh-Hans', '文具店'),
  ('shop.newsagent', 'en', 'Newsagent'),
  ('shop.newsagent', 'ar', 'كشك صحف'),
  ('shop.newsagent', 'bn', 'খবরের কাগজের দোকান'),
  ('shop.newsagent', 'ca', 'Quiosc'),
  ('shop.newsagent', 'de', 'Kiosk'),
  ('shop.newsagent', 'es', 'Quiosco'),
  ('shop.newsagent', 'fr', 'Presse'),
  ('shop.newsagent', 'hi', 'अख़बार की दुकान'),
  ('shop.newsagent', 'ja', '売店'),
  ('shop.newsagent', 'pt-BR', 'Banca de jornal'),
  ('shop.newsagent', 'ru', 'Газетный киоск'),
  ('shop.newsagent', 'zh-Hans', '报刊亭'),
  ('shop.tobacco', 'en', 'Tobacconist'),
  ('shop.tobacco', 'ar', 'محل تبغ'),
  ('shop.tobacco', 'bn', 'তামাকের দোকান'),
  ('shop.tobacco', 'ca', 'Estanc'),
  ('shop.tobacco', 'de', 'Tabakladen'),
  ('shop.tobacco', 'es', 'Estanco'),
  ('shop.tobacco', 'fr', 'Bureau de tabac'),
  ('shop.tobacco', 'hi', 'तंबाकू की दुकान'),
  ('shop.tobacco', 'ja', 'たばこ店'),
  ('shop.tobacco', 'pt-BR', 'Tabacaria'),
  ('shop.tobacco', 'ru', 'Табак'),
  ('shop.tobacco', 'zh-Hans', '烟草店'),
  ('shop.pet', 'en', 'Pet shop'),
  ('shop.pet', 'ar', 'متجر حيوانات أليفة'),
  ('shop.pet', 'bn', 'পোষা প্রাণীর দোকান'),
  ('shop.pet', 'ca', 'Botiga d''animals'),
  ('shop.pet', 'de', 'Tierbedarf'),
  ('shop.pet', 'es', 'Tienda de mascotas'),
  ('shop.pet', 'fr', 'Animalerie'),
  ('shop.pet', 'hi', 'पेट शॉप'),
  ('shop.pet', 'ja', 'ペットショップ'),
  ('shop.pet', 'pt-BR', 'Pet shop'),
  ('shop.pet', 'ru', 'Зоомагазин'),
  ('shop.pet', 'zh-Hans', '宠物店'),
  ('shop.laundry', 'en', 'Laundry'),
  ('shop.laundry', 'ar', 'مغسلة'),
  ('shop.laundry', 'bn', 'লন্ড্রি'),
  ('shop.laundry', 'ca', 'Bugaderia'),
  ('shop.laundry', 'de', 'Wäscherei'),
  ('shop.laundry', 'es', 'Lavandería'),
  ('shop.laundry', 'fr', 'Laverie'),
  ('shop.laundry', 'hi', 'लॉन्ड्री'),
  ('shop.laundry', 'ja', 'クリーニング'),
  ('shop.laundry', 'pt-BR', 'Lavanderia'),
  ('shop.laundry', 'ru', 'Прачечная'),
  ('shop.laundry', 'zh-Hans', '洗衣店'),
  ('shop.second_hand', 'en', 'Second-hand'),
  ('shop.second_hand', 'ar', 'سلع مستعملة'),
  ('shop.second_hand', 'bn', 'সেকেন্ড-হ্যান্ড'),
  ('shop.second_hand', 'ca', 'Segona mà'),
  ('shop.second_hand', 'de', 'Second-Hand'),
  ('shop.second_hand', 'es', 'Segunda mano'),
  ('shop.second_hand', 'fr', 'Seconde main'),
  ('shop.second_hand', 'hi', 'सेकंड-हैंड'),
  ('shop.second_hand', 'ja', 'リサイクル・古物'),
  ('shop.second_hand', 'pt-BR', 'Brechó'),
  ('shop.second_hand', 'ru', 'Секонд-хенд'),
  ('shop.second_hand', 'zh-Hans', '二手店'),
  ('shop.art', 'en', 'Art & framing'),
  ('shop.art', 'ar', 'فنون وتأطير'),
  ('shop.art', 'bn', 'শিল্পকর্ম ও ফ্রেমিং'),
  ('shop.art', 'ca', 'Art i marcs'),
  ('shop.art', 'de', 'Kunst & Rahmen'),
  ('shop.art', 'es', 'Arte y marcos'),
  ('shop.art', 'fr', 'Art et encadrement'),
  ('shop.art', 'hi', 'आर्ट और फ़्रेमिंग'),
  ('shop.art', 'ja', '画材・額縁'),
  ('shop.art', 'pt-BR', 'Arte e molduras'),
  ('shop.art', 'ru', 'Искусство и багет'),
  ('shop.art', 'zh-Hans', '艺术品装裱'),
  ('shop.travel_agency', 'en', 'Travel agency'),
  ('shop.travel_agency', 'ar', 'وكالة سفر'),
  ('shop.travel_agency', 'bn', 'ট্রাভেল এজেন্সি'),
  ('shop.travel_agency', 'ca', 'Agència de viatges'),
  ('shop.travel_agency', 'de', 'Reisebüro'),
  ('shop.travel_agency', 'es', 'Agencia de viajes'),
  ('shop.travel_agency', 'fr', 'Agence de voyages'),
  ('shop.travel_agency', 'hi', 'ट्रैवल एजेंसी'),
  ('shop.travel_agency', 'ja', '旅行代理店'),
  ('shop.travel_agency', 'pt-BR', 'Agência de viagens'),
  ('shop.travel_agency', 'ru', 'Турагентство'),
  ('shop.travel_agency', 'zh-Hans', '旅行社'),
  ('lodging', 'en', 'Stay'),
  ('lodging', 'ar', 'إقامة'),
  ('lodging', 'bn', 'থাকার জায়গা'),
  ('lodging', 'ca', 'Allotjament'),
  ('lodging', 'de', 'Unterkunft'),
  ('lodging', 'es', 'Alojamiento'),
  ('lodging', 'fr', 'Hébergement'),
  ('lodging', 'hi', 'ठहरने की जगह'),
  ('lodging', 'ja', '宿泊'),
  ('lodging', 'pt-BR', 'Hospedagem'),
  ('lodging', 'ru', 'Жильё'),
  ('lodging', 'zh-Hans', '住宿'),
  ('lodging.hotel', 'en', 'Hotel'),
  ('lodging.hotel', 'ar', 'فندق'),
  ('lodging.hotel', 'bn', 'হোটেল'),
  ('lodging.hotel', 'ca', 'Hotel'),
  ('lodging.hotel', 'de', 'Hotel'),
  ('lodging.hotel', 'es', 'Hotel'),
  ('lodging.hotel', 'fr', 'Hôtel'),
  ('lodging.hotel', 'hi', 'होटल'),
  ('lodging.hotel', 'ja', 'ホテル'),
  ('lodging.hotel', 'pt-BR', 'Hotel'),
  ('lodging.hotel', 'ru', 'Отель'),
  ('lodging.hotel', 'zh-Hans', '酒店'),
  ('lodging.hostel', 'en', 'Hostel'),
  ('lodging.hostel', 'ar', 'نزل'),
  ('lodging.hostel', 'bn', 'হোস্টেল'),
  ('lodging.hostel', 'ca', 'Alberg'),
  ('lodging.hostel', 'de', 'Hostel'),
  ('lodging.hostel', 'es', 'Albergue'),
  ('lodging.hostel', 'fr', 'Auberge de jeunesse'),
  ('lodging.hostel', 'hi', 'हॉस्टल'),
  ('lodging.hostel', 'ja', 'ホステル'),
  ('lodging.hostel', 'pt-BR', 'Hostel'),
  ('lodging.hostel', 'ru', 'Хостел'),
  ('lodging.hostel', 'zh-Hans', '青年旅舍'),
  ('lodging.guest_house', 'en', 'Guest house'),
  ('lodging.guest_house', 'ar', 'دار ضيافة'),
  ('lodging.guest_house', 'bn', 'গেস্ট হাউস'),
  ('lodging.guest_house', 'ca', 'Casa d''hostes'),
  ('lodging.guest_house', 'de', 'Pension'),
  ('lodging.guest_house', 'es', 'Casa de huéspedes'),
  ('lodging.guest_house', 'fr', 'Chambre d''hôtes'),
  ('lodging.guest_house', 'hi', 'गेस्ट हाउस'),
  ('lodging.guest_house', 'ja', '民宿・ゲストハウス'),
  ('lodging.guest_house', 'pt-BR', 'Pousada'),
  ('lodging.guest_house', 'ru', 'Гостевой дом'),
  ('lodging.guest_house', 'zh-Hans', '民宿'),
  ('lodging.apartment', 'en', 'Holiday apartment'),
  ('lodging.apartment', 'ar', 'شقة سياحية'),
  ('lodging.apartment', 'bn', 'হলিডে অ্যাপার্টমেন্ট'),
  ('lodging.apartment', 'ca', 'Apartament turístic'),
  ('lodging.apartment', 'de', 'Ferienwohnung'),
  ('lodging.apartment', 'es', 'Apartamento turístico'),
  ('lodging.apartment', 'fr', 'Appartement de vacances'),
  ('lodging.apartment', 'hi', 'हॉलिडे अपार्टमेंट'),
  ('lodging.apartment', 'ja', '貸別荘・アパートメント'),
  ('lodging.apartment', 'pt-BR', 'Apartamento de temporada'),
  ('lodging.apartment', 'ru', 'Апартаменты'),
  ('lodging.apartment', 'zh-Hans', '度假公寓'),
  ('lodging.camping', 'en', 'Campsite'),
  ('lodging.camping', 'ar', 'مخيم'),
  ('lodging.camping', 'bn', 'ক্যাম্পসাইট'),
  ('lodging.camping', 'ca', 'Càmping'),
  ('lodging.camping', 'de', 'Campingplatz'),
  ('lodging.camping', 'es', 'Cámping'),
  ('lodging.camping', 'fr', 'Camping'),
  ('lodging.camping', 'hi', 'कैंपसाइट'),
  ('lodging.camping', 'ja', 'キャンプ場'),
  ('lodging.camping', 'pt-BR', 'Camping'),
  ('lodging.camping', 'ru', 'Кемпинг'),
  ('lodging.camping', 'zh-Hans', '露营地'),
  ('lodging.hut', 'en', 'Mountain hut'),
  ('lodging.hut', 'ar', 'كوخ جبلي'),
  ('lodging.hut', 'bn', 'পাহাড়ি কুটির'),
  ('lodging.hut', 'ca', 'Refugi'),
  ('lodging.hut', 'de', 'Berghütte'),
  ('lodging.hut', 'es', 'Refugio'),
  ('lodging.hut', 'fr', 'Refuge'),
  ('lodging.hut', 'hi', 'पहाड़ी झोपड़ी'),
  ('lodging.hut', 'ja', '山小屋'),
  ('lodging.hut', 'pt-BR', 'Abrigo de montanha'),
  ('lodging.hut', 'ru', 'Горный приют'),
  ('lodging.hut', 'zh-Hans', '山间小屋'),
  ('leisure', 'en', 'Leisure'),
  ('leisure', 'ar', 'ترفيه'),
  ('leisure', 'bn', 'অবসর'),
  ('leisure', 'ca', 'Lleure'),
  ('leisure', 'de', 'Freizeit'),
  ('leisure', 'es', 'Ocio'),
  ('leisure', 'fr', 'Loisirs'),
  ('leisure', 'hi', 'मनोरंजन'),
  ('leisure', 'ja', 'レジャー'),
  ('leisure', 'pt-BR', 'Lazer'),
  ('leisure', 'ru', 'Досуг'),
  ('leisure', 'zh-Hans', '休闲'),
  ('leisure.park', 'en', 'Park'),
  ('leisure.park', 'ar', 'منتزه'),
  ('leisure.park', 'bn', 'পার্ক'),
  ('leisure.park', 'ca', 'Parc'),
  ('leisure.park', 'de', 'Park'),
  ('leisure.park', 'es', 'Parque'),
  ('leisure.park', 'fr', 'Parc'),
  ('leisure.park', 'hi', 'पार्क'),
  ('leisure.park', 'ja', '公園'),
  ('leisure.park', 'pt-BR', 'Parque'),
  ('leisure.park', 'ru', 'Парк'),
  ('leisure.park', 'zh-Hans', '公园'),
  ('leisure.garden', 'en', 'Garden'),
  ('leisure.garden', 'ar', 'حديقة'),
  ('leisure.garden', 'bn', 'বাগান'),
  ('leisure.garden', 'ca', 'Jardí'),
  ('leisure.garden', 'de', 'Garten'),
  ('leisure.garden', 'es', 'Jardín'),
  ('leisure.garden', 'fr', 'Jardin'),
  ('leisure.garden', 'hi', 'बगीचा'),
  ('leisure.garden', 'ja', '庭園'),
  ('leisure.garden', 'pt-BR', 'Jardim'),
  ('leisure.garden', 'ru', 'Сад'),
  ('leisure.garden', 'zh-Hans', '花园'),
  ('leisure.playground', 'en', 'Playground'),
  ('leisure.playground', 'ar', 'ملعب أطفال'),
  ('leisure.playground', 'bn', 'খেলার মাঠ'),
  ('leisure.playground', 'ca', 'Parc infantil'),
  ('leisure.playground', 'de', 'Spielplatz'),
  ('leisure.playground', 'es', 'Parque infantil'),
  ('leisure.playground', 'fr', 'Aire de jeux'),
  ('leisure.playground', 'hi', 'खेल का मैदान'),
  ('leisure.playground', 'ja', '遊び場'),
  ('leisure.playground', 'pt-BR', 'Parquinho'),
  ('leisure.playground', 'ru', 'Детская площадка'),
  ('leisure.playground', 'zh-Hans', '儿童游乐场'),
  ('leisure.dog_park', 'en', 'Dog park'),
  ('leisure.dog_park', 'ar', 'حديقة كلاب'),
  ('leisure.dog_park', 'bn', 'ডগ পার্ক'),
  ('leisure.dog_park', 'ca', 'Àrea per a gossos'),
  ('leisure.dog_park', 'de', 'Hundewiese'),
  ('leisure.dog_park', 'es', 'Parque para perros'),
  ('leisure.dog_park', 'fr', 'Parc canin'),
  ('leisure.dog_park', 'hi', 'डॉग पार्क'),
  ('leisure.dog_park', 'ja', 'ドッグラン'),
  ('leisure.dog_park', 'pt-BR', 'Parque para cães'),
  ('leisure.dog_park', 'ru', 'Площадка для собак'),
  ('leisure.dog_park', 'zh-Hans', '狗狗公园'),
  ('leisure.picnic_site', 'en', 'Picnic area'),
  ('leisure.picnic_site', 'ar', 'منطقة نزهة'),
  ('leisure.picnic_site', 'bn', 'পিকনিক স্পট'),
  ('leisure.picnic_site', 'ca', 'Zona de pícnic'),
  ('leisure.picnic_site', 'de', 'Picknickplatz'),
  ('leisure.picnic_site', 'es', 'Zona de pícnic'),
  ('leisure.picnic_site', 'fr', 'Aire de pique-nique'),
  ('leisure.picnic_site', 'hi', 'पिकनिक स्पॉट'),
  ('leisure.picnic_site', 'ja', 'ピクニック場'),
  ('leisure.picnic_site', 'pt-BR', 'Área de piquenique'),
  ('leisure.picnic_site', 'ru', 'Место для пикника'),
  ('leisure.picnic_site', 'zh-Hans', '野餐区'),
  ('leisure.nature_reserve', 'en', 'Nature reserve'),
  ('leisure.nature_reserve', 'ar', 'محمية طبيعية'),
  ('leisure.nature_reserve', 'bn', 'প্রাকৃতিক সংরক্ষিত এলাকা'),
  ('leisure.nature_reserve', 'ca', 'Reserva natural'),
  ('leisure.nature_reserve', 'de', 'Naturschutzgebiet'),
  ('leisure.nature_reserve', 'es', 'Reserva natural'),
  ('leisure.nature_reserve', 'fr', 'Réserve naturelle'),
  ('leisure.nature_reserve', 'hi', 'प्रकृति अभयारण्य'),
  ('leisure.nature_reserve', 'ja', '自然保護区'),
  ('leisure.nature_reserve', 'pt-BR', 'Reserva natural'),
  ('leisure.nature_reserve', 'ru', 'Заповедник'),
  ('leisure.nature_reserve', 'zh-Hans', '自然保护区'),
  ('leisure.beach', 'en', 'Beach'),
  ('leisure.beach', 'ar', 'شاطئ'),
  ('leisure.beach', 'bn', 'সমুদ্রসৈকত'),
  ('leisure.beach', 'ca', 'Platja'),
  ('leisure.beach', 'de', 'Strand'),
  ('leisure.beach', 'es', 'Playa'),
  ('leisure.beach', 'fr', 'Plage'),
  ('leisure.beach', 'hi', 'बीच'),
  ('leisure.beach', 'ja', 'ビーチ'),
  ('leisure.beach', 'pt-BR', 'Praia'),
  ('leisure.beach', 'ru', 'Пляж'),
  ('leisure.beach', 'zh-Hans', '海滩'),
  ('leisure.marina', 'en', 'Marina'),
  ('leisure.marina', 'ar', 'مرسى'),
  ('leisure.marina', 'bn', 'মেরিনা'),
  ('leisure.marina', 'ca', 'Port esportiu'),
  ('leisure.marina', 'de', 'Jachthafen'),
  ('leisure.marina', 'es', 'Puerto deportivo'),
  ('leisure.marina', 'fr', 'Port de plaisance'),
  ('leisure.marina', 'hi', 'मरीना'),
  ('leisure.marina', 'ja', 'マリーナ'),
  ('leisure.marina', 'pt-BR', 'Marina'),
  ('leisure.marina', 'ru', 'Яхтенная гавань'),
  ('leisure.marina', 'zh-Hans', '游艇码头'),
  ('leisure.water', 'en', 'Lake or reservoir'),
  ('leisure.water', 'ar', 'بحيرة أو خزان مائي'),
  ('leisure.water', 'bn', 'হ্রদ বা জলাধার'),
  ('leisure.water', 'ca', 'Llac o embassament'),
  ('leisure.water', 'de', 'See oder Stausee'),
  ('leisure.water', 'es', 'Lago o embalse'),
  ('leisure.water', 'fr', 'Lac ou réservoir'),
  ('leisure.water', 'hi', 'झील या जलाशय'),
  ('leisure.water', 'ja', '湖・貯水池'),
  ('leisure.water', 'pt-BR', 'Lago ou represa'),
  ('leisure.water', 'ru', 'Озеро или водохранилище'),
  ('leisure.water', 'zh-Hans', '湖泊水库'),
  ('leisure.amusement', 'en', 'Amusement'),
  ('leisure.amusement', 'ar', 'تسلية'),
  ('leisure.amusement', 'bn', 'বিনোদন'),
  ('leisure.amusement', 'ca', 'Entreteniment'),
  ('leisure.amusement', 'de', 'Unterhaltung'),
  ('leisure.amusement', 'es', 'Entretenimiento'),
  ('leisure.amusement', 'fr', 'Divertissement'),
  ('leisure.amusement', 'hi', 'मनोरंजन स्थल'),
  ('leisure.amusement', 'ja', 'アミューズメント'),
  ('leisure.amusement', 'pt-BR', 'Diversão'),
  ('leisure.amusement', 'ru', 'Развлечения'),
  ('leisure.amusement', 'zh-Hans', '游乐娱乐'),
  ('leisure.fitness', 'en', 'Gym'),
  ('leisure.fitness', 'ar', 'صالة رياضية'),
  ('leisure.fitness', 'bn', 'জিম'),
  ('leisure.fitness', 'ca', 'Gimnàs'),
  ('leisure.fitness', 'de', 'Fitnessstudio'),
  ('leisure.fitness', 'es', 'Gimnasio'),
  ('leisure.fitness', 'fr', 'Salle de sport'),
  ('leisure.fitness', 'hi', 'जिम'),
  ('leisure.fitness', 'ja', 'ジム'),
  ('leisure.fitness', 'pt-BR', 'Academia'),
  ('leisure.fitness', 'ru', 'Спортзал'),
  ('leisure.fitness', 'zh-Hans', '健身房'),
  ('sport', 'en', 'Sport'),
  ('sport', 'ar', 'رياضة'),
  ('sport', 'bn', 'খেলাধুলা'),
  ('sport', 'ca', 'Esport'),
  ('sport', 'de', 'Sport'),
  ('sport', 'es', 'Deporte'),
  ('sport', 'fr', 'Sport'),
  ('sport', 'hi', 'खेल'),
  ('sport', 'ja', 'スポーツ'),
  ('sport', 'pt-BR', 'Esporte'),
  ('sport', 'ru', 'Спорт'),
  ('sport', 'zh-Hans', '运动'),
  ('sport.centre', 'en', 'Sports centre'),
  ('sport.centre', 'ar', 'مركز رياضي'),
  ('sport.centre', 'bn', 'স্পোর্টস সেন্টার'),
  ('sport.centre', 'ca', 'Poliesportiu'),
  ('sport.centre', 'de', 'Sportzentrum'),
  ('sport.centre', 'es', 'Polideportivo'),
  ('sport.centre', 'fr', 'Centre sportif'),
  ('sport.centre', 'hi', 'स्पोर्ट्स सेंटर'),
  ('sport.centre', 'ja', 'スポーツセンター'),
  ('sport.centre', 'pt-BR', 'Centro esportivo'),
  ('sport.centre', 'ru', 'Спортивный центр'),
  ('sport.centre', 'zh-Hans', '体育中心'),
  ('sport.pitch', 'en', 'Sports pitch'),
  ('sport.pitch', 'ar', 'ملعب رياضي'),
  ('sport.pitch', 'bn', 'খেলার কোর্ট'),
  ('sport.pitch', 'ca', 'Pista esportiva'),
  ('sport.pitch', 'de', 'Sportplatz'),
  ('sport.pitch', 'es', 'Pista deportiva'),
  ('sport.pitch', 'fr', 'Terrain de sport'),
  ('sport.pitch', 'hi', 'खेल का कोर्ट'),
  ('sport.pitch', 'ja', '競技場'),
  ('sport.pitch', 'pt-BR', 'Quadra esportiva'),
  ('sport.pitch', 'ru', 'Спортплощадка'),
  ('sport.pitch', 'zh-Hans', '运动场'),
  ('sport.stadium', 'en', 'Stadium'),
  ('sport.stadium', 'ar', 'استاد'),
  ('sport.stadium', 'bn', 'স্টেডিয়াম'),
  ('sport.stadium', 'ca', 'Estadi'),
  ('sport.stadium', 'de', 'Stadion'),
  ('sport.stadium', 'es', 'Estadio'),
  ('sport.stadium', 'fr', 'Stade'),
  ('sport.stadium', 'hi', 'स्टेडियम'),
  ('sport.stadium', 'ja', 'スタジアム'),
  ('sport.stadium', 'pt-BR', 'Estádio'),
  ('sport.stadium', 'ru', 'Стадион'),
  ('sport.stadium', 'zh-Hans', '体育场'),
  ('sport.swimming', 'en', 'Swimming pool'),
  ('sport.swimming', 'ar', 'مسبح'),
  ('sport.swimming', 'bn', 'সুইমিং পুল'),
  ('sport.swimming', 'ca', 'Piscina'),
  ('sport.swimming', 'de', 'Schwimmbad'),
  ('sport.swimming', 'es', 'Piscina'),
  ('sport.swimming', 'fr', 'Piscine'),
  ('sport.swimming', 'hi', 'स्विमिंग पूल'),
  ('sport.swimming', 'ja', 'プール'),
  ('sport.swimming', 'pt-BR', 'Piscina'),
  ('sport.swimming', 'ru', 'Бассейн'),
  ('sport.swimming', 'zh-Hans', '游泳馆'),
  ('sport.golf', 'en', 'Golf'),
  ('sport.golf', 'ar', 'غولف'),
  ('sport.golf', 'bn', 'গলফ'),
  ('sport.golf', 'ca', 'Golf'),
  ('sport.golf', 'de', 'Golf'),
  ('sport.golf', 'es', 'Golf'),
  ('sport.golf', 'fr', 'Golf'),
  ('sport.golf', 'hi', 'गोल्फ़'),
  ('sport.golf', 'ja', 'ゴルフ'),
  ('sport.golf', 'pt-BR', 'Golfe'),
  ('sport.golf', 'ru', 'Гольф'),
  ('sport.golf', 'zh-Hans', '高尔夫'),
  ('sport.ice_rink', 'en', 'Ice rink'),
  ('sport.ice_rink', 'ar', 'حلبة تزلج على الجليد'),
  ('sport.ice_rink', 'bn', 'আইস রিঙ্ক'),
  ('sport.ice_rink', 'ca', 'Pista de gel'),
  ('sport.ice_rink', 'de', 'Eisbahn'),
  ('sport.ice_rink', 'es', 'Pista de hielo'),
  ('sport.ice_rink', 'fr', 'Patinoire'),
  ('sport.ice_rink', 'hi', 'आइस रिंक'),
  ('sport.ice_rink', 'ja', 'スケートリンク'),
  ('sport.ice_rink', 'pt-BR', 'Pista de patinação no gelo'),
  ('sport.ice_rink', 'ru', 'Каток'),
  ('sport.ice_rink', 'zh-Hans', '滑冰场'),
  ('sport.horse_riding', 'en', 'Horse riding'),
  ('sport.horse_riding', 'ar', 'ركوب الخيل'),
  ('sport.horse_riding', 'bn', 'ঘোড়ায় চড়া'),
  ('sport.horse_riding', 'ca', 'Hípica'),
  ('sport.horse_riding', 'de', 'Reiten'),
  ('sport.horse_riding', 'es', 'Hípica'),
  ('sport.horse_riding', 'fr', 'Équitation'),
  ('sport.horse_riding', 'hi', 'घुड़सवारी'),
  ('sport.horse_riding', 'ja', '乗馬'),
  ('sport.horse_riding', 'pt-BR', 'Hipismo'),
  ('sport.horse_riding', 'ru', 'Конный спорт'),
  ('sport.horse_riding', 'zh-Hans', '马术'),
  ('sport.climbing', 'en', 'Climbing'),
  ('sport.climbing', 'ar', 'تسلق'),
  ('sport.climbing', 'bn', 'ক্লাইম্বিং'),
  ('sport.climbing', 'ca', 'Escalada'),
  ('sport.climbing', 'de', 'Klettern'),
  ('sport.climbing', 'es', 'Escalada'),
  ('sport.climbing', 'fr', 'Escalade'),
  ('sport.climbing', 'hi', 'क्लाइम्बिंग'),
  ('sport.climbing', 'ja', 'クライミング'),
  ('sport.climbing', 'pt-BR', 'Escalada'),
  ('sport.climbing', 'ru', 'Скалолазание'),
  ('sport.climbing', 'zh-Hans', '攀岩'),
  ('sport.skiing', 'en', 'Skiing'),
  ('sport.skiing', 'ar', 'تزلج'),
  ('sport.skiing', 'bn', 'স্কিইং'),
  ('sport.skiing', 'ca', 'Esquí'),
  ('sport.skiing', 'de', 'Skifahren'),
  ('sport.skiing', 'es', 'Esquí'),
  ('sport.skiing', 'fr', 'Ski'),
  ('sport.skiing', 'hi', 'स्कीइंग'),
  ('sport.skiing', 'ja', 'スキー'),
  ('sport.skiing', 'pt-BR', 'Esqui'),
  ('sport.skiing', 'ru', 'Лыжи'),
  ('sport.skiing', 'zh-Hans', '滑雪'),
  ('culture', 'en', 'Culture & sights'),
  ('culture', 'ar', 'ثقافة ومعالم'),
  ('culture', 'bn', 'সংস্কৃতি ও দর্শনীয় স্থান'),
  ('culture', 'ca', 'Cultura i turisme'),
  ('culture', 'de', 'Kultur & Sehenswertes'),
  ('culture', 'es', 'Cultura y turismo'),
  ('culture', 'fr', 'Culture et visites'),
  ('culture', 'hi', 'संस्कृति और दर्शनीय स्थल'),
  ('culture', 'ja', '文化・観光'),
  ('culture', 'pt-BR', 'Cultura e turismo'),
  ('culture', 'ru', 'Культура и достопримечательности'),
  ('culture', 'zh-Hans', '文化景点'),
  ('culture.museum', 'en', 'Museum'),
  ('culture.museum', 'ar', 'متحف'),
  ('culture.museum', 'bn', 'জাদুঘর'),
  ('culture.museum', 'ca', 'Museu'),
  ('culture.museum', 'de', 'Museum'),
  ('culture.museum', 'es', 'Museo'),
  ('culture.museum', 'fr', 'Musée'),
  ('culture.museum', 'hi', 'संग्रहालय'),
  ('culture.museum', 'ja', '博物館・美術館'),
  ('culture.museum', 'pt-BR', 'Museu'),
  ('culture.museum', 'ru', 'Музей'),
  ('culture.museum', 'zh-Hans', '博物馆'),
  ('culture.gallery', 'en', 'Gallery'),
  ('culture.gallery', 'ar', 'معرض فني'),
  ('culture.gallery', 'bn', 'গ্যালারি'),
  ('culture.gallery', 'ca', 'Galeria'),
  ('culture.gallery', 'de', 'Galerie'),
  ('culture.gallery', 'es', 'Galería'),
  ('culture.gallery', 'fr', 'Galerie'),
  ('culture.gallery', 'hi', 'गैलरी'),
  ('culture.gallery', 'ja', 'ギャラリー'),
  ('culture.gallery', 'pt-BR', 'Galeria'),
  ('culture.gallery', 'ru', 'Галерея'),
  ('culture.gallery', 'zh-Hans', '美术馆'),
  ('culture.theatre', 'en', 'Theatre'),
  ('culture.theatre', 'ar', 'مسرح'),
  ('culture.theatre', 'bn', 'থিয়েটার'),
  ('culture.theatre', 'ca', 'Teatre'),
  ('culture.theatre', 'de', 'Theater'),
  ('culture.theatre', 'es', 'Teatro'),
  ('culture.theatre', 'fr', 'Théâtre'),
  ('culture.theatre', 'hi', 'थिएटर'),
  ('culture.theatre', 'ja', '劇場'),
  ('culture.theatre', 'pt-BR', 'Teatro'),
  ('culture.theatre', 'ru', 'Театр'),
  ('culture.theatre', 'zh-Hans', '剧院'),
  ('culture.cinema', 'en', 'Cinema'),
  ('culture.cinema', 'ar', 'سينما'),
  ('culture.cinema', 'bn', 'সিনেমা হল'),
  ('culture.cinema', 'ca', 'Cinema'),
  ('culture.cinema', 'de', 'Kino'),
  ('culture.cinema', 'es', 'Cine'),
  ('culture.cinema', 'fr', 'Cinéma'),
  ('culture.cinema', 'hi', 'सिनेमा'),
  ('culture.cinema', 'ja', '映画館'),
  ('culture.cinema', 'pt-BR', 'Cinema'),
  ('culture.cinema', 'ru', 'Кинотеатр'),
  ('culture.cinema', 'zh-Hans', '电影院'),
  ('culture.music_venue', 'en', 'Music venue'),
  ('culture.music_venue', 'ar', 'قاعة حفلات'),
  ('culture.music_venue', 'bn', 'মিউজিক ভেন্যু'),
  ('culture.music_venue', 'ca', 'Sala de concerts'),
  ('culture.music_venue', 'de', 'Konzertsaal'),
  ('culture.music_venue', 'es', 'Sala de conciertos'),
  ('culture.music_venue', 'fr', 'Salle de concert'),
  ('culture.music_venue', 'hi', 'म्यूज़िक वेन्यू'),
  ('culture.music_venue', 'ja', 'ライブハウス・ホール'),
  ('culture.music_venue', 'pt-BR', 'Casa de shows'),
  ('culture.music_venue', 'ru', 'Концертный зал'),
  ('culture.music_venue', 'zh-Hans', '音乐厅'),
  ('culture.attraction', 'en', 'Attraction'),
  ('culture.attraction', 'ar', 'معلم سياحي'),
  ('culture.attraction', 'bn', 'দর্শনীয় স্থান'),
  ('culture.attraction', 'ca', 'Atracció'),
  ('culture.attraction', 'de', 'Sehenswürdigkeit'),
  ('culture.attraction', 'es', 'Atracción'),
  ('culture.attraction', 'fr', 'Attraction'),
  ('culture.attraction', 'hi', 'पर्यटन स्थल'),
  ('culture.attraction', 'ja', '観光スポット'),
  ('culture.attraction', 'pt-BR', 'Atração'),
  ('culture.attraction', 'ru', 'Достопримечательность'),
  ('culture.attraction', 'zh-Hans', '景点'),
  ('culture.viewpoint', 'en', 'Viewpoint'),
  ('culture.viewpoint', 'ar', 'نقطة إطلالة'),
  ('culture.viewpoint', 'bn', 'ভিউপয়েন্ট'),
  ('culture.viewpoint', 'ca', 'Mirador'),
  ('culture.viewpoint', 'de', 'Aussichtspunkt'),
  ('culture.viewpoint', 'es', 'Mirador'),
  ('culture.viewpoint', 'fr', 'Point de vue'),
  ('culture.viewpoint', 'hi', 'व्यूपॉइंट'),
  ('culture.viewpoint', 'ja', '展望スポット'),
  ('culture.viewpoint', 'pt-BR', 'Mirante'),
  ('culture.viewpoint', 'ru', 'Смотровая площадка'),
  ('culture.viewpoint', 'zh-Hans', '观景台'),
  ('culture.artwork', 'en', 'Public art'),
  ('culture.artwork', 'ar', 'فن عام'),
  ('culture.artwork', 'bn', 'পাবলিক আর্ট'),
  ('culture.artwork', 'ca', 'Art públic'),
  ('culture.artwork', 'de', 'Kunst im öffentlichen Raum'),
  ('culture.artwork', 'es', 'Arte público'),
  ('culture.artwork', 'fr', 'Art public'),
  ('culture.artwork', 'hi', 'सार्वजनिक कला'),
  ('culture.artwork', 'ja', 'パブリックアート'),
  ('culture.artwork', 'pt-BR', 'Arte pública'),
  ('culture.artwork', 'ru', 'Объекты искусства'),
  ('culture.artwork', 'zh-Hans', '公共艺术'),
  ('culture.zoo', 'en', 'Zoo'),
  ('culture.zoo', 'ar', 'حديقة حيوان'),
  ('culture.zoo', 'bn', 'চিড়িয়াখানা'),
  ('culture.zoo', 'ca', 'Zoo'),
  ('culture.zoo', 'de', 'Zoo'),
  ('culture.zoo', 'es', 'Zoo'),
  ('culture.zoo', 'fr', 'Zoo'),
  ('culture.zoo', 'hi', 'चिड़ियाघर'),
  ('culture.zoo', 'ja', '動物園'),
  ('culture.zoo', 'pt-BR', 'Zoológico'),
  ('culture.zoo', 'ru', 'Зоопарк'),
  ('culture.zoo', 'zh-Hans', '动物园'),
  ('culture.aquarium', 'en', 'Aquarium'),
  ('culture.aquarium', 'ar', 'أكواريوم'),
  ('culture.aquarium', 'bn', 'অ্যাকোয়ারিয়াম'),
  ('culture.aquarium', 'ca', 'Aquari'),
  ('culture.aquarium', 'de', 'Aquarium'),
  ('culture.aquarium', 'es', 'Acuario'),
  ('culture.aquarium', 'fr', 'Aquarium'),
  ('culture.aquarium', 'hi', 'एक्वेरियम'),
  ('culture.aquarium', 'ja', '水族館'),
  ('culture.aquarium', 'pt-BR', 'Aquário'),
  ('culture.aquarium', 'ru', 'Океанариум'),
  ('culture.aquarium', 'zh-Hans', '水族馆'),
  ('culture.information', 'en', 'Tourist information'),
  ('culture.information', 'ar', 'معلومات سياحية'),
  ('culture.information', 'bn', 'পর্যটন তথ্যকেন্দ্র'),
  ('culture.information', 'ca', 'Informació turística'),
  ('culture.information', 'de', 'Touristeninformation'),
  ('culture.information', 'es', 'Información turística'),
  ('culture.information', 'fr', 'Office de tourisme'),
  ('culture.information', 'hi', 'पर्यटक सूचना केंद्र'),
  ('culture.information', 'ja', '観光案内所'),
  ('culture.information', 'pt-BR', 'Informações turísticas'),
  ('culture.information', 'ru', 'Туристическая информация'),
  ('culture.information', 'zh-Hans', '游客中心'),
  ('culture.historic', 'en', 'Historic site'),
  ('culture.historic', 'ar', 'موقع تاريخي'),
  ('culture.historic', 'bn', 'ঐতিহাসিক স্থান'),
  ('culture.historic', 'ca', 'Lloc històric'),
  ('culture.historic', 'de', 'Historische Stätte'),
  ('culture.historic', 'es', 'Sitio histórico'),
  ('culture.historic', 'fr', 'Site historique'),
  ('culture.historic', 'hi', 'ऐतिहासिक स्थल'),
  ('culture.historic', 'ja', '史跡'),
  ('culture.historic', 'pt-BR', 'Local histórico'),
  ('culture.historic', 'ru', 'Историческое место'),
  ('culture.historic', 'zh-Hans', '历史遗迹'),
  ('culture.monument', 'en', 'Monument'),
  ('culture.monument', 'ar', 'نصب تذكاري'),
  ('culture.monument', 'bn', 'স্মৃতিস্তম্ভ'),
  ('culture.monument', 'ca', 'Monument'),
  ('culture.monument', 'de', 'Denkmal'),
  ('culture.monument', 'es', 'Monumento'),
  ('culture.monument', 'fr', 'Monument'),
  ('culture.monument', 'hi', 'स्मारक'),
  ('culture.monument', 'ja', '記念碑'),
  ('culture.monument', 'pt-BR', 'Monumento'),
  ('culture.monument', 'ru', 'Памятник'),
  ('culture.monument', 'zh-Hans', '纪念碑'),
  ('culture.castle', 'en', 'Castle'),
  ('culture.castle', 'ar', 'قلعة'),
  ('culture.castle', 'bn', 'দুর্গ'),
  ('culture.castle', 'ca', 'Castell'),
  ('culture.castle', 'de', 'Burg'),
  ('culture.castle', 'es', 'Castillo'),
  ('culture.castle', 'fr', 'Château'),
  ('culture.castle', 'hi', 'क़िला'),
  ('culture.castle', 'ja', '城'),
  ('culture.castle', 'pt-BR', 'Castelo'),
  ('culture.castle', 'ru', 'Замок'),
  ('culture.castle', 'zh-Hans', '城堡'),
  ('culture.archaeological_site', 'en', 'Archaeological site'),
  ('culture.archaeological_site', 'ar', 'موقع أثري'),
  ('culture.archaeological_site', 'bn', 'প্রত্নতাত্ত্বিক স্থান'),
  ('culture.archaeological_site', 'ca', 'Jaciment arqueològic'),
  ('culture.archaeological_site', 'de', 'Ausgrabungsstätte'),
  ('culture.archaeological_site', 'es', 'Yacimiento arqueológico'),
  ('culture.archaeological_site', 'fr', 'Site archéologique'),
  ('culture.archaeological_site', 'hi', 'पुरातात्विक स्थल'),
  ('culture.archaeological_site', 'ja', '遺跡'),
  ('culture.archaeological_site', 'pt-BR', 'Sítio arqueológico'),
  ('culture.archaeological_site', 'ru', 'Археологический памятник'),
  ('culture.archaeological_site', 'zh-Hans', '考古遗址'),
  ('transport', 'en', 'Transport'),
  ('transport', 'ar', 'مواصلات'),
  ('transport', 'bn', 'পরিবহন'),
  ('transport', 'ca', 'Transport'),
  ('transport', 'de', 'Verkehr'),
  ('transport', 'es', 'Transporte'),
  ('transport', 'fr', 'Transports'),
  ('transport', 'hi', 'परिवहन'),
  ('transport', 'ja', '交通'),
  ('transport', 'pt-BR', 'Transporte'),
  ('transport', 'ru', 'Транспорт'),
  ('transport', 'zh-Hans', '交通'),
  ('transport.bus_stop', 'en', 'Bus stop'),
  ('transport.bus_stop', 'ar', 'موقف حافلات'),
  ('transport.bus_stop', 'bn', 'বাস স্টপ'),
  ('transport.bus_stop', 'ca', 'Parada d''autobús'),
  ('transport.bus_stop', 'de', 'Bushaltestelle'),
  ('transport.bus_stop', 'es', 'Parada de autobús'),
  ('transport.bus_stop', 'fr', 'Arrêt de bus'),
  ('transport.bus_stop', 'hi', 'बस स्टॉप'),
  ('transport.bus_stop', 'ja', 'バス停'),
  ('transport.bus_stop', 'pt-BR', 'Ponto de ônibus'),
  ('transport.bus_stop', 'ru', 'Автобусная остановка'),
  ('transport.bus_stop', 'zh-Hans', '公交站'),
  ('transport.bus_station', 'en', 'Bus station'),
  ('transport.bus_station', 'ar', 'محطة حافلات'),
  ('transport.bus_station', 'bn', 'বাস টার্মিনাল'),
  ('transport.bus_station', 'ca', 'Estació d''autobusos'),
  ('transport.bus_station', 'de', 'Busbahnhof'),
  ('transport.bus_station', 'es', 'Estación de autobuses'),
  ('transport.bus_station', 'fr', 'Gare routière'),
  ('transport.bus_station', 'hi', 'बस अड्डा'),
  ('transport.bus_station', 'ja', 'バスターミナル'),
  ('transport.bus_station', 'pt-BR', 'Rodoviária'),
  ('transport.bus_station', 'ru', 'Автовокзал'),
  ('transport.bus_station', 'zh-Hans', '汽车站'),
  ('transport.rail_station', 'en', 'Train station'),
  ('transport.rail_station', 'ar', 'محطة قطار'),
  ('transport.rail_station', 'bn', 'রেলস্টেশন'),
  ('transport.rail_station', 'ca', 'Estació de tren'),
  ('transport.rail_station', 'de', 'Bahnhof'),
  ('transport.rail_station', 'es', 'Estación de tren'),
  ('transport.rail_station', 'fr', 'Gare'),
  ('transport.rail_station', 'hi', 'रेलवे स्टेशन'),
  ('transport.rail_station', 'ja', '駅'),
  ('transport.rail_station', 'pt-BR', 'Estação de trem'),
  ('transport.rail_station', 'ru', 'Ж/д станция'),
  ('transport.rail_station', 'zh-Hans', '火车站'),
  ('transport.tram_stop', 'en', 'Tram stop'),
  ('transport.tram_stop', 'ar', 'موقف ترام'),
  ('transport.tram_stop', 'bn', 'ট্রাম স্টপ'),
  ('transport.tram_stop', 'ca', 'Parada de tramvia'),
  ('transport.tram_stop', 'de', 'Straßenbahnhaltestelle'),
  ('transport.tram_stop', 'es', 'Parada de tranvía'),
  ('transport.tram_stop', 'fr', 'Arrêt de tram'),
  ('transport.tram_stop', 'hi', 'ट्राम स्टॉप'),
  ('transport.tram_stop', 'ja', '路面電車停留所'),
  ('transport.tram_stop', 'pt-BR', 'Parada de bonde'),
  ('transport.tram_stop', 'ru', 'Трамвайная остановка'),
  ('transport.tram_stop', 'zh-Hans', '有轨电车站'),
  ('transport.aerialway', 'en', 'Cable car'),
  ('transport.aerialway', 'ar', 'تلفريك'),
  ('transport.aerialway', 'bn', 'কেবল কার'),
  ('transport.aerialway', 'ca', 'Telefèric'),
  ('transport.aerialway', 'de', 'Seilbahn'),
  ('transport.aerialway', 'es', 'Teleférico'),
  ('transport.aerialway', 'fr', 'Téléphérique'),
  ('transport.aerialway', 'hi', 'केबल कार'),
  ('transport.aerialway', 'ja', 'ロープウェイ'),
  ('transport.aerialway', 'pt-BR', 'Teleférico'),
  ('transport.aerialway', 'ru', 'Канатная дорога'),
  ('transport.aerialway', 'zh-Hans', '缆车'),
  ('transport.ferry_terminal', 'en', 'Ferry terminal'),
  ('transport.ferry_terminal', 'ar', 'محطة عبارات'),
  ('transport.ferry_terminal', 'bn', 'ফেরিঘাট'),
  ('transport.ferry_terminal', 'ca', 'Terminal de ferris'),
  ('transport.ferry_terminal', 'de', 'Fähranleger'),
  ('transport.ferry_terminal', 'es', 'Terminal de ferris'),
  ('transport.ferry_terminal', 'fr', 'Gare maritime'),
  ('transport.ferry_terminal', 'hi', 'फ़ेरी टर्मिनल'),
  ('transport.ferry_terminal', 'ja', 'フェリーターミナル'),
  ('transport.ferry_terminal', 'pt-BR', 'Terminal de balsas'),
  ('transport.ferry_terminal', 'ru', 'Паромный терминал'),
  ('transport.ferry_terminal', 'zh-Hans', '轮渡码头'),
  ('transport.taxi', 'en', 'Taxi rank'),
  ('transport.taxi', 'ar', 'موقف سيارات أجرة'),
  ('transport.taxi', 'bn', 'ট্যাক্সি স্ট্যান্ড'),
  ('transport.taxi', 'ca', 'Parada de taxis'),
  ('transport.taxi', 'de', 'Taxistand'),
  ('transport.taxi', 'es', 'Parada de taxis'),
  ('transport.taxi', 'fr', 'Station de taxis'),
  ('transport.taxi', 'hi', 'टैक्सी स्टैंड'),
  ('transport.taxi', 'ja', 'タクシー乗り場'),
  ('transport.taxi', 'pt-BR', 'Ponto de táxi'),
  ('transport.taxi', 'ru', 'Стоянка такси'),
  ('transport.taxi', 'zh-Hans', '出租车站'),
  ('transport.bicycle_rental', 'en', 'Bike hire'),
  ('transport.bicycle_rental', 'ar', 'تأجير دراجات'),
  ('transport.bicycle_rental', 'bn', 'সাইকেল ভাড়া'),
  ('transport.bicycle_rental', 'ca', 'Lloguer de bicicletes'),
  ('transport.bicycle_rental', 'de', 'Fahrradverleih'),
  ('transport.bicycle_rental', 'es', 'Alquiler de bicicletas'),
  ('transport.bicycle_rental', 'fr', 'Location de vélos'),
  ('transport.bicycle_rental', 'hi', 'किराये पर साइकिल'),
  ('transport.bicycle_rental', 'ja', 'レンタサイクル'),
  ('transport.bicycle_rental', 'pt-BR', 'Aluguel de bicicletas'),
  ('transport.bicycle_rental', 'ru', 'Прокат велосипедов'),
  ('transport.bicycle_rental', 'zh-Hans', '自行车租赁'),
  ('transport.car_rental', 'en', 'Car hire'),
  ('transport.car_rental', 'ar', 'تأجير سيارات'),
  ('transport.car_rental', 'bn', 'গাড়ি ভাড়া'),
  ('transport.car_rental', 'ca', 'Lloguer de cotxes'),
  ('transport.car_rental', 'de', 'Autovermietung'),
  ('transport.car_rental', 'es', 'Alquiler de coches'),
  ('transport.car_rental', 'fr', 'Location de voitures'),
  ('transport.car_rental', 'hi', 'किराये पर कार'),
  ('transport.car_rental', 'ja', 'レンタカー'),
  ('transport.car_rental', 'pt-BR', 'Aluguel de carros'),
  ('transport.car_rental', 'ru', 'Прокат автомобилей'),
  ('transport.car_rental', 'zh-Hans', '租车'),
  ('vehicle', 'en', 'Car & vehicle'),
  ('vehicle', 'ar', 'سيارات ومركبات'),
  ('vehicle', 'bn', 'গাড়ি ও যানবাহন'),
  ('vehicle', 'ca', 'Vehicles'),
  ('vehicle', 'de', 'Auto & Fahrzeuge'),
  ('vehicle', 'es', 'Vehículos'),
  ('vehicle', 'fr', 'Véhicules'),
  ('vehicle', 'hi', 'कार और वाहन'),
  ('vehicle', 'ja', '車・バイク'),
  ('vehicle', 'pt-BR', 'Veículos'),
  ('vehicle', 'ru', 'Автомобили'),
  ('vehicle', 'zh-Hans', '汽车服务'),
  ('vehicle.fuel', 'en', 'Petrol station'),
  ('vehicle.fuel', 'ar', 'محطة وقود'),
  ('vehicle.fuel', 'bn', 'পেট্রোল পাম্প'),
  ('vehicle.fuel', 'ca', 'Benzinera'),
  ('vehicle.fuel', 'de', 'Tankstelle'),
  ('vehicle.fuel', 'es', 'Gasolinera'),
  ('vehicle.fuel', 'fr', 'Station-service'),
  ('vehicle.fuel', 'hi', 'पेट्रोल पंप'),
  ('vehicle.fuel', 'ja', 'ガソリンスタンド'),
  ('vehicle.fuel', 'pt-BR', 'Posto de gasolina'),
  ('vehicle.fuel', 'ru', 'АЗС'),
  ('vehicle.fuel', 'zh-Hans', '加油站'),
  ('vehicle.charging', 'en', 'EV charging'),
  ('vehicle.charging', 'ar', 'شحن السيارات الكهربائية'),
  ('vehicle.charging', 'bn', 'EV চার্জিং'),
  ('vehicle.charging', 'ca', 'Recàrrega elèctrica'),
  ('vehicle.charging', 'de', 'Ladestation'),
  ('vehicle.charging', 'es', 'Recarga eléctrica'),
  ('vehicle.charging', 'fr', 'Recharge électrique'),
  ('vehicle.charging', 'hi', 'EV चार्जिंग'),
  ('vehicle.charging', 'ja', 'EV充電'),
  ('vehicle.charging', 'pt-BR', 'Recarga de veículos elétricos'),
  ('vehicle.charging', 'ru', 'Зарядка электромобилей'),
  ('vehicle.charging', 'zh-Hans', '充电站'),
  ('vehicle.parking', 'en', 'Parking'),
  ('vehicle.parking', 'ar', 'موقف سيارات'),
  ('vehicle.parking', 'bn', 'পার্কিং'),
  ('vehicle.parking', 'ca', 'Aparcament'),
  ('vehicle.parking', 'de', 'Parkplatz'),
  ('vehicle.parking', 'es', 'Aparcamiento'),
  ('vehicle.parking', 'fr', 'Parking'),
  ('vehicle.parking', 'hi', 'पार्किंग'),
  ('vehicle.parking', 'ja', '駐車場'),
  ('vehicle.parking', 'pt-BR', 'Estacionamento'),
  ('vehicle.parking', 'ru', 'Парковка'),
  ('vehicle.parking', 'zh-Hans', '停车场'),
  ('vehicle.repair', 'en', 'Car repair'),
  ('vehicle.repair', 'ar', 'إصلاح سيارات'),
  ('vehicle.repair', 'bn', 'গাড়ি মেরামত'),
  ('vehicle.repair', 'ca', 'Taller mecànic'),
  ('vehicle.repair', 'de', 'Autowerkstatt'),
  ('vehicle.repair', 'es', 'Taller mecánico'),
  ('vehicle.repair', 'fr', 'Garage'),
  ('vehicle.repair', 'hi', 'कार रिपेयर'),
  ('vehicle.repair', 'ja', '自動車整備'),
  ('vehicle.repair', 'pt-BR', 'Oficina mecânica'),
  ('vehicle.repair', 'ru', 'Автосервис'),
  ('vehicle.repair', 'zh-Hans', '汽车维修'),
  ('vehicle.dealer', 'en', 'Car dealer'),
  ('vehicle.dealer', 'ar', 'معرض سيارات'),
  ('vehicle.dealer', 'bn', 'গাড়ির ডিলার'),
  ('vehicle.dealer', 'ca', 'Concessionari'),
  ('vehicle.dealer', 'de', 'Autohaus'),
  ('vehicle.dealer', 'es', 'Concesionario'),
  ('vehicle.dealer', 'fr', 'Concessionnaire'),
  ('vehicle.dealer', 'hi', 'कार डीलर'),
  ('vehicle.dealer', 'ja', 'カーディーラー'),
  ('vehicle.dealer', 'pt-BR', 'Concessionária'),
  ('vehicle.dealer', 'ru', 'Автосалон'),
  ('vehicle.dealer', 'zh-Hans', '汽车销售'),
  ('vehicle.car_wash', 'en', 'Car wash'),
  ('vehicle.car_wash', 'ar', 'غسيل سيارات'),
  ('vehicle.car_wash', 'bn', 'কার ওয়াশ'),
  ('vehicle.car_wash', 'ca', 'Rentat de cotxes'),
  ('vehicle.car_wash', 'de', 'Autowäsche'),
  ('vehicle.car_wash', 'es', 'Lavado de coches'),
  ('vehicle.car_wash', 'fr', 'Lavage auto'),
  ('vehicle.car_wash', 'hi', 'कार वॉश'),
  ('vehicle.car_wash', 'ja', '洗車'),
  ('vehicle.car_wash', 'pt-BR', 'Lava-rápido'),
  ('vehicle.car_wash', 'ru', 'Автомойка'),
  ('vehicle.car_wash', 'zh-Hans', '洗车'),
  ('vehicle.motorcycle', 'en', 'Motorcycles'),
  ('vehicle.motorcycle', 'ar', 'دراجات نارية'),
  ('vehicle.motorcycle', 'bn', 'মোটরসাইকেল'),
  ('vehicle.motorcycle', 'ca', 'Motos'),
  ('vehicle.motorcycle', 'de', 'Motorräder'),
  ('vehicle.motorcycle', 'es', 'Motos'),
  ('vehicle.motorcycle', 'fr', 'Motos'),
  ('vehicle.motorcycle', 'hi', 'मोटरसाइकिल'),
  ('vehicle.motorcycle', 'ja', 'バイク'),
  ('vehicle.motorcycle', 'pt-BR', 'Motos'),
  ('vehicle.motorcycle', 'ru', 'Мотоциклы'),
  ('vehicle.motorcycle', 'zh-Hans', '摩托车'),
  ('health', 'en', 'Health'),
  ('health', 'ar', 'صحة'),
  ('health', 'bn', 'স্বাস্থ্য'),
  ('health', 'ca', 'Salut'),
  ('health', 'de', 'Gesundheit'),
  ('health', 'es', 'Salud'),
  ('health', 'fr', 'Santé'),
  ('health', 'hi', 'स्वास्थ्य'),
  ('health', 'ja', '医療'),
  ('health', 'pt-BR', 'Saúde'),
  ('health', 'ru', 'Здоровье'),
  ('health', 'zh-Hans', '医疗'),
  ('health.hospital', 'en', 'Hospital'),
  ('health.hospital', 'ar', 'مستشفى'),
  ('health.hospital', 'bn', 'হাসপাতাল'),
  ('health.hospital', 'ca', 'Hospital'),
  ('health.hospital', 'de', 'Krankenhaus'),
  ('health.hospital', 'es', 'Hospital'),
  ('health.hospital', 'fr', 'Hôpital'),
  ('health.hospital', 'hi', 'अस्पताल'),
  ('health.hospital', 'ja', '病院'),
  ('health.hospital', 'pt-BR', 'Hospital'),
  ('health.hospital', 'ru', 'Больница'),
  ('health.hospital', 'zh-Hans', '医院'),
  ('health.clinic', 'en', 'Clinic'),
  ('health.clinic', 'ar', 'عيادة'),
  ('health.clinic', 'bn', 'ক্লিনিক'),
  ('health.clinic', 'ca', 'Centre de salut'),
  ('health.clinic', 'de', 'Klinik'),
  ('health.clinic', 'es', 'Centro de salud'),
  ('health.clinic', 'fr', 'Centre médical'),
  ('health.clinic', 'hi', 'क्लिनिक'),
  ('health.clinic', 'ja', '診療所'),
  ('health.clinic', 'pt-BR', 'Clínica'),
  ('health.clinic', 'ru', 'Поликлиника'),
  ('health.clinic', 'zh-Hans', '诊所'),
  ('health.doctor', 'en', 'Doctor'),
  ('health.doctor', 'ar', 'طبيب'),
  ('health.doctor', 'bn', 'ডাক্তার'),
  ('health.doctor', 'ca', 'Metge'),
  ('health.doctor', 'de', 'Arzt'),
  ('health.doctor', 'es', 'Médico'),
  ('health.doctor', 'fr', 'Médecin'),
  ('health.doctor', 'hi', 'डॉक्टर'),
  ('health.doctor', 'ja', '医院'),
  ('health.doctor', 'pt-BR', 'Médico'),
  ('health.doctor', 'ru', 'Врач'),
  ('health.doctor', 'zh-Hans', '门诊'),
  ('health.dentist', 'en', 'Dentist'),
  ('health.dentist', 'ar', 'طبيب أسنان'),
  ('health.dentist', 'bn', 'দাঁতের ডাক্তার'),
  ('health.dentist', 'ca', 'Dentista'),
  ('health.dentist', 'de', 'Zahnarzt'),
  ('health.dentist', 'es', 'Dentista'),
  ('health.dentist', 'fr', 'Dentiste'),
  ('health.dentist', 'hi', 'डेंटिस्ट'),
  ('health.dentist', 'ja', '歯科'),
  ('health.dentist', 'pt-BR', 'Dentista'),
  ('health.dentist', 'ru', 'Стоматология'),
  ('health.dentist', 'zh-Hans', '牙科'),
  ('health.pharmacy', 'en', 'Pharmacy'),
  ('health.pharmacy', 'ar', 'صيدلية'),
  ('health.pharmacy', 'bn', 'ওষুধের দোকান'),
  ('health.pharmacy', 'ca', 'Farmàcia'),
  ('health.pharmacy', 'de', 'Apotheke'),
  ('health.pharmacy', 'es', 'Farmacia'),
  ('health.pharmacy', 'fr', 'Pharmacie'),
  ('health.pharmacy', 'hi', 'फ़ार्मेसी'),
  ('health.pharmacy', 'ja', '薬局'),
  ('health.pharmacy', 'pt-BR', 'Farmácia'),
  ('health.pharmacy', 'ru', 'Аптека'),
  ('health.pharmacy', 'zh-Hans', '药店'),
  ('health.veterinary', 'en', 'Vet'),
  ('health.veterinary', 'ar', 'طبيب بيطري'),
  ('health.veterinary', 'bn', 'পশু চিকিৎসক'),
  ('health.veterinary', 'ca', 'Veterinari'),
  ('health.veterinary', 'de', 'Tierarzt'),
  ('health.veterinary', 'es', 'Veterinario'),
  ('health.veterinary', 'fr', 'Vétérinaire'),
  ('health.veterinary', 'hi', 'पशु चिकित्सक'),
  ('health.veterinary', 'ja', '動物病院'),
  ('health.veterinary', 'pt-BR', 'Veterinário'),
  ('health.veterinary', 'ru', 'Ветклиника'),
  ('health.veterinary', 'zh-Hans', '宠物医院'),
  ('health.care_home', 'en', 'Care home'),
  ('health.care_home', 'ar', 'دار رعاية'),
  ('health.care_home', 'bn', 'কেয়ার হোম'),
  ('health.care_home', 'ca', 'Residència'),
  ('health.care_home', 'de', 'Pflegeheim'),
  ('health.care_home', 'es', 'Residencia'),
  ('health.care_home', 'fr', 'Maison de retraite'),
  ('health.care_home', 'hi', 'केयर होम'),
  ('health.care_home', 'ja', '介護施設'),
  ('health.care_home', 'pt-BR', 'Casa de repouso'),
  ('health.care_home', 'ru', 'Дом престарелых'),
  ('health.care_home', 'zh-Hans', '养老院'),
  ('education', 'en', 'Education'),
  ('education', 'ar', 'تعليم'),
  ('education', 'bn', 'শিক্ষা'),
  ('education', 'ca', 'Educació'),
  ('education', 'de', 'Bildung'),
  ('education', 'es', 'Educación'),
  ('education', 'fr', 'Éducation'),
  ('education', 'hi', 'शिक्षा'),
  ('education', 'ja', '教育'),
  ('education', 'pt-BR', 'Educação'),
  ('education', 'ru', 'Образование'),
  ('education', 'zh-Hans', '教育'),
  ('education.school', 'en', 'School'),
  ('education.school', 'ar', 'مدرسة'),
  ('education.school', 'bn', 'স্কুল'),
  ('education.school', 'ca', 'Escola'),
  ('education.school', 'de', 'Schule'),
  ('education.school', 'es', 'Escuela'),
  ('education.school', 'fr', 'École'),
  ('education.school', 'hi', 'स्कूल'),
  ('education.school', 'ja', '学校'),
  ('education.school', 'pt-BR', 'Escola'),
  ('education.school', 'ru', 'Школа'),
  ('education.school', 'zh-Hans', '学校'),
  ('education.kindergarten', 'en', 'Nursery'),
  ('education.kindergarten', 'ar', 'حضانة'),
  ('education.kindergarten', 'bn', 'নার্সারি'),
  ('education.kindergarten', 'ca', 'Llar d''infants'),
  ('education.kindergarten', 'de', 'Kita'),
  ('education.kindergarten', 'es', 'Guardería'),
  ('education.kindergarten', 'fr', 'Crèche'),
  ('education.kindergarten', 'hi', 'नर्सरी'),
  ('education.kindergarten', 'ja', '保育園・幼稚園'),
  ('education.kindergarten', 'pt-BR', 'Creche'),
  ('education.kindergarten', 'ru', 'Детский сад'),
  ('education.kindergarten', 'zh-Hans', '幼儿园'),
  ('education.university', 'en', 'University'),
  ('education.university', 'ar', 'جامعة'),
  ('education.university', 'bn', 'বিশ্ববিদ্যালয়'),
  ('education.university', 'ca', 'Universitat'),
  ('education.university', 'de', 'Universität'),
  ('education.university', 'es', 'Universidad'),
  ('education.university', 'fr', 'Université'),
  ('education.university', 'hi', 'विश्वविद्यालय'),
  ('education.university', 'ja', '大学'),
  ('education.university', 'pt-BR', 'Universidade'),
  ('education.university', 'ru', 'Университет'),
  ('education.university', 'zh-Hans', '大学'),
  ('education.library', 'en', 'Library'),
  ('education.library', 'ar', 'مكتبة'),
  ('education.library', 'bn', 'গ্রন্থাগার'),
  ('education.library', 'ca', 'Biblioteca'),
  ('education.library', 'de', 'Bibliothek'),
  ('education.library', 'es', 'Biblioteca'),
  ('education.library', 'fr', 'Bibliothèque'),
  ('education.library', 'hi', 'लाइब्रेरी'),
  ('education.library', 'ja', '図書館'),
  ('education.library', 'pt-BR', 'Biblioteca'),
  ('education.library', 'ru', 'Библиотека'),
  ('education.library', 'zh-Hans', '图书馆'),
  ('education.training', 'en', 'Courses & training'),
  ('education.training', 'ar', 'دورات وتدريب'),
  ('education.training', 'bn', 'কোর্স ও প্রশিক্ষণ'),
  ('education.training', 'ca', 'Formació'),
  ('education.training', 'de', 'Kurse & Weiterbildung'),
  ('education.training', 'es', 'Formación'),
  ('education.training', 'fr', 'Cours et formations'),
  ('education.training', 'hi', 'कोर्स और ट्रेनिंग'),
  ('education.training', 'ja', 'スクール・教室'),
  ('education.training', 'pt-BR', 'Cursos e formação'),
  ('education.training', 'ru', 'Курсы и обучение'),
  ('education.training', 'zh-Hans', '培训机构'),
  ('civic', 'en', 'Public services'),
  ('civic', 'ar', 'خدمات عامة'),
  ('civic', 'bn', 'সরকারি পরিষেবা'),
  ('civic', 'ca', 'Serveis públics'),
  ('civic', 'de', 'Öffentliche Einrichtungen'),
  ('civic', 'es', 'Servicios públicos'),
  ('civic', 'fr', 'Services publics'),
  ('civic', 'hi', 'सार्वजनिक सेवाएँ'),
  ('civic', 'ja', '公共施設'),
  ('civic', 'pt-BR', 'Serviços públicos'),
  ('civic', 'ru', 'Госучреждения'),
  ('civic', 'zh-Hans', '公共服务'),
  ('civic.townhall', 'en', 'Town hall'),
  ('civic.townhall', 'ar', 'مبنى البلدية'),
  ('civic.townhall', 'bn', 'পৌরসভা'),
  ('civic.townhall', 'ca', 'Ajuntament'),
  ('civic.townhall', 'de', 'Rathaus'),
  ('civic.townhall', 'es', 'Ayuntamiento'),
  ('civic.townhall', 'fr', 'Mairie'),
  ('civic.townhall', 'hi', 'नगर निगम कार्यालय'),
  ('civic.townhall', 'ja', '市役所'),
  ('civic.townhall', 'pt-BR', 'Prefeitura'),
  ('civic.townhall', 'ru', 'Мэрия'),
  ('civic.townhall', 'zh-Hans', '市政厅'),
  ('civic.courthouse', 'en', 'Courthouse'),
  ('civic.courthouse', 'ar', 'محكمة'),
  ('civic.courthouse', 'bn', 'আদালত'),
  ('civic.courthouse', 'ca', 'Jutjat'),
  ('civic.courthouse', 'de', 'Gericht'),
  ('civic.courthouse', 'es', 'Juzgado'),
  ('civic.courthouse', 'fr', 'Tribunal'),
  ('civic.courthouse', 'hi', 'अदालत'),
  ('civic.courthouse', 'ja', '裁判所'),
  ('civic.courthouse', 'pt-BR', 'Fórum'),
  ('civic.courthouse', 'ru', 'Суд'),
  ('civic.courthouse', 'zh-Hans', '法院'),
  ('civic.police', 'en', 'Police'),
  ('civic.police', 'ar', 'شرطة'),
  ('civic.police', 'bn', 'পুলিশ'),
  ('civic.police', 'ca', 'Policia'),
  ('civic.police', 'de', 'Polizei'),
  ('civic.police', 'es', 'Policía'),
  ('civic.police', 'fr', 'Police'),
  ('civic.police', 'hi', 'पुलिस'),
  ('civic.police', 'ja', '警察'),
  ('civic.police', 'pt-BR', 'Polícia'),
  ('civic.police', 'ru', 'Полиция'),
  ('civic.police', 'zh-Hans', '警察'),
  ('civic.fire_station', 'en', 'Fire station'),
  ('civic.fire_station', 'ar', 'مركز إطفاء'),
  ('civic.fire_station', 'bn', 'ফায়ার স্টেশন'),
  ('civic.fire_station', 'ca', 'Bombers'),
  ('civic.fire_station', 'de', 'Feuerwehr'),
  ('civic.fire_station', 'es', 'Bomberos'),
  ('civic.fire_station', 'fr', 'Pompiers'),
  ('civic.fire_station', 'hi', 'फ़ायर स्टेशन'),
  ('civic.fire_station', 'ja', '消防署'),
  ('civic.fire_station', 'pt-BR', 'Corpo de Bombeiros'),
  ('civic.fire_station', 'ru', 'Пожарная часть'),
  ('civic.fire_station', 'zh-Hans', '消防站'),
  ('civic.post_office', 'en', 'Post office'),
  ('civic.post_office', 'ar', 'مكتب بريد'),
  ('civic.post_office', 'bn', 'ডাকঘর'),
  ('civic.post_office', 'ca', 'Oficina de correus'),
  ('civic.post_office', 'de', 'Post'),
  ('civic.post_office', 'es', 'Oficina de correos'),
  ('civic.post_office', 'fr', 'Bureau de poste'),
  ('civic.post_office', 'hi', 'डाकघर'),
  ('civic.post_office', 'ja', '郵便局'),
  ('civic.post_office', 'pt-BR', 'Agência dos Correios'),
  ('civic.post_office', 'ru', 'Почта'),
  ('civic.post_office', 'zh-Hans', '邮局'),
  ('civic.post_box', 'en', 'Post box'),
  ('civic.post_box', 'ar', 'صندوق بريد'),
  ('civic.post_box', 'bn', 'ডাকবাক্স'),
  ('civic.post_box', 'ca', 'Bústia'),
  ('civic.post_box', 'de', 'Briefkasten'),
  ('civic.post_box', 'es', 'Buzón'),
  ('civic.post_box', 'fr', 'Boîte aux lettres'),
  ('civic.post_box', 'hi', 'पोस्ट बॉक्स'),
  ('civic.post_box', 'ja', '郵便ポスト'),
  ('civic.post_box', 'pt-BR', 'Caixa de correio'),
  ('civic.post_box', 'ru', 'Почтовый ящик'),
  ('civic.post_box', 'zh-Hans', '邮筒'),
  ('civic.community_centre', 'en', 'Community centre'),
  ('civic.community_centre', 'ar', 'مركز مجتمعي'),
  ('civic.community_centre', 'bn', 'কমিউনিটি সেন্টার'),
  ('civic.community_centre', 'ca', 'Centre cívic'),
  ('civic.community_centre', 'de', 'Gemeindezentrum'),
  ('civic.community_centre', 'es', 'Centro cívico'),
  ('civic.community_centre', 'fr', 'Maison de quartier'),
  ('civic.community_centre', 'hi', 'सामुदायिक केंद्र'),
  ('civic.community_centre', 'ja', '公民館'),
  ('civic.community_centre', 'pt-BR', 'Centro comunitário'),
  ('civic.community_centre', 'ru', 'Общественный центр'),
  ('civic.community_centre', 'zh-Hans', '社区中心'),
  ('civic.embassy', 'en', 'Embassy'),
  ('civic.embassy', 'ar', 'سفارة'),
  ('civic.embassy', 'bn', 'দূতাবাস'),
  ('civic.embassy', 'ca', 'Ambaixada'),
  ('civic.embassy', 'de', 'Botschaft'),
  ('civic.embassy', 'es', 'Embajada'),
  ('civic.embassy', 'fr', 'Ambassade'),
  ('civic.embassy', 'hi', 'दूतावास'),
  ('civic.embassy', 'ja', '大使館'),
  ('civic.embassy', 'pt-BR', 'Embaixada'),
  ('civic.embassy', 'ru', 'Посольство'),
  ('civic.embassy', 'zh-Hans', '大使馆'),
  ('civic.toilets', 'en', 'Toilets'),
  ('civic.toilets', 'ar', 'دورات مياه'),
  ('civic.toilets', 'bn', 'শৌচাগার'),
  ('civic.toilets', 'ca', 'Lavabos'),
  ('civic.toilets', 'de', 'Toiletten'),
  ('civic.toilets', 'es', 'Aseos'),
  ('civic.toilets', 'fr', 'Toilettes'),
  ('civic.toilets', 'hi', 'शौचालय'),
  ('civic.toilets', 'ja', 'トイレ'),
  ('civic.toilets', 'pt-BR', 'Banheiros'),
  ('civic.toilets', 'ru', 'Туалеты'),
  ('civic.toilets', 'zh-Hans', '公共厕所'),
  ('civic.cemetery', 'en', 'Cemetery'),
  ('civic.cemetery', 'ar', 'مقبرة'),
  ('civic.cemetery', 'bn', 'কবরস্থান'),
  ('civic.cemetery', 'ca', 'Cementiri'),
  ('civic.cemetery', 'de', 'Friedhof'),
  ('civic.cemetery', 'es', 'Cementerio'),
  ('civic.cemetery', 'fr', 'Cimetière'),
  ('civic.cemetery', 'hi', 'क़ब्रिस्तान'),
  ('civic.cemetery', 'ja', '墓地'),
  ('civic.cemetery', 'pt-BR', 'Cemitério'),
  ('civic.cemetery', 'ru', 'Кладбище'),
  ('civic.cemetery', 'zh-Hans', '墓地'),
  ('finance', 'en', 'Money'),
  ('finance', 'ar', 'خدمات مالية'),
  ('finance', 'bn', 'টাকাপয়সা'),
  ('finance', 'ca', 'Diners'),
  ('finance', 'de', 'Geld'),
  ('finance', 'es', 'Dinero'),
  ('finance', 'fr', 'Argent'),
  ('finance', 'hi', 'पैसा'),
  ('finance', 'ja', 'お金'),
  ('finance', 'pt-BR', 'Dinheiro'),
  ('finance', 'ru', 'Деньги'),
  ('finance', 'zh-Hans', '金融'),
  ('finance.bank', 'en', 'Bank'),
  ('finance.bank', 'ar', 'بنك'),
  ('finance.bank', 'bn', 'ব্যাংক'),
  ('finance.bank', 'ca', 'Banc'),
  ('finance.bank', 'de', 'Bank'),
  ('finance.bank', 'es', 'Banco'),
  ('finance.bank', 'fr', 'Banque'),
  ('finance.bank', 'hi', 'बैंक'),
  ('finance.bank', 'ja', '銀行'),
  ('finance.bank', 'pt-BR', 'Banco'),
  ('finance.bank', 'ru', 'Банк'),
  ('finance.bank', 'zh-Hans', '银行'),
  ('finance.atm', 'en', 'Cash machine'),
  ('finance.atm', 'ar', 'صراف آلي'),
  ('finance.atm', 'bn', 'এটিএম'),
  ('finance.atm', 'ca', 'Caixer automàtic'),
  ('finance.atm', 'de', 'Geldautomat'),
  ('finance.atm', 'es', 'Cajero automático'),
  ('finance.atm', 'fr', 'Distributeur de billets'),
  ('finance.atm', 'hi', 'एटीएम'),
  ('finance.atm', 'ja', 'ATM'),
  ('finance.atm', 'pt-BR', 'Caixa eletrônico'),
  ('finance.atm', 'ru', 'Банкомат'),
  ('finance.atm', 'zh-Hans', 'ATM'),
  ('finance.exchange', 'en', 'Currency exchange'),
  ('finance.exchange', 'ar', 'صرافة عملات'),
  ('finance.exchange', 'bn', 'মুদ্রা বিনিময়'),
  ('finance.exchange', 'ca', 'Canvi de divises'),
  ('finance.exchange', 'de', 'Wechselstube'),
  ('finance.exchange', 'es', 'Cambio de divisas'),
  ('finance.exchange', 'fr', 'Bureau de change'),
  ('finance.exchange', 'hi', 'मुद्रा विनिमय'),
  ('finance.exchange', 'ja', '両替所'),
  ('finance.exchange', 'pt-BR', 'Casa de câmbio'),
  ('finance.exchange', 'ru', 'Обмен валюты'),
  ('finance.exchange', 'zh-Hans', '外币兑换'),
  ('worship', 'en', 'Place of worship'),
  ('worship', 'ar', 'دار عبادة'),
  ('worship', 'bn', 'উপাসনালয়'),
  ('worship', 'ca', 'Lloc de culte'),
  ('worship', 'de', 'Gotteshaus'),
  ('worship', 'es', 'Lugar de culto'),
  ('worship', 'fr', 'Lieu de culte'),
  ('worship', 'hi', 'पूजा स्थल'),
  ('worship', 'ja', '宗教施設'),
  ('worship', 'pt-BR', 'Local de culto'),
  ('worship', 'ru', 'Место поклонения'),
  ('worship', 'zh-Hans', '宗教场所'),
  ('services', 'en', 'Services'),
  ('services', 'ar', 'خدمات'),
  ('services', 'bn', 'পরিষেবা'),
  ('services', 'ca', 'Serveis'),
  ('services', 'de', 'Dienstleistungen'),
  ('services', 'es', 'Servicios'),
  ('services', 'fr', 'Services'),
  ('services', 'hi', 'सेवाएँ'),
  ('services', 'ja', 'サービス'),
  ('services', 'pt-BR', 'Serviços'),
  ('services', 'ru', 'Услуги'),
  ('services', 'zh-Hans', '生活服务'),
  ('office', 'en', 'Offices'),
  ('office', 'ar', 'مكاتب'),
  ('office', 'bn', 'অফিস'),
  ('office', 'ca', 'Oficines'),
  ('office', 'de', 'Büros'),
  ('office', 'es', 'Oficinas'),
  ('office', 'fr', 'Bureaux'),
  ('office', 'hi', 'दफ़्तर'),
  ('office', 'ja', 'オフィス'),
  ('office', 'pt-BR', 'Escritórios'),
  ('office', 'ru', 'Офисы'),
  ('office', 'zh-Hans', '办公'),
  ('office.coworking', 'en', 'Coworking'),
  ('office.coworking', 'ar', 'مساحة عمل مشتركة'),
  ('office.coworking', 'bn', 'কো-ওয়ার্কিং'),
  ('office.coworking', 'ca', 'Coworking'),
  ('office.coworking', 'de', 'Coworking'),
  ('office.coworking', 'es', 'Coworking'),
  ('office.coworking', 'fr', 'Coworking'),
  ('office.coworking', 'hi', 'को-वर्किंग'),
  ('office.coworking', 'ja', 'コワーキング'),
  ('office.coworking', 'pt-BR', 'Coworking'),
  ('office.coworking', 'ru', 'Коворкинг'),
  ('office.coworking', 'zh-Hans', '联合办公'),
  ('office.company', 'en', 'Company'),
  ('office.company', 'ar', 'شركة'),
  ('office.company', 'bn', 'কোম্পানি'),
  ('office.company', 'ca', 'Empresa'),
  ('office.company', 'de', 'Unternehmen'),
  ('office.company', 'es', 'Empresa'),
  ('office.company', 'fr', 'Entreprise'),
  ('office.company', 'hi', 'कंपनी'),
  ('office.company', 'ja', '企業'),
  ('office.company', 'pt-BR', 'Empresa'),
  ('office.company', 'ru', 'Компания'),
  ('office.company', 'zh-Hans', '公司'),
  ('office.government', 'en', 'Government office'),
  ('office.government', 'ar', 'مكتب حكومي'),
  ('office.government', 'bn', 'সরকারি অফিস'),
  ('office.government', 'ca', 'Oficina pública'),
  ('office.government', 'de', 'Behörde'),
  ('office.government', 'es', 'Oficina pública'),
  ('office.government', 'fr', 'Administration'),
  ('office.government', 'hi', 'सरकारी दफ़्तर'),
  ('office.government', 'ja', '官公庁'),
  ('office.government', 'pt-BR', 'Órgão público'),
  ('office.government', 'ru', 'Госучреждение'),
  ('office.government', 'zh-Hans', '政府机关'),
  ('office.estate_agent', 'en', 'Estate agent'),
  ('office.estate_agent', 'ar', 'مكتب عقارات'),
  ('office.estate_agent', 'bn', 'রিয়েল এস্টেট এজেন্ট'),
  ('office.estate_agent', 'ca', 'Immobiliària'),
  ('office.estate_agent', 'de', 'Immobilienmakler'),
  ('office.estate_agent', 'es', 'Inmobiliaria'),
  ('office.estate_agent', 'fr', 'Agence immobilière'),
  ('office.estate_agent', 'hi', 'प्रॉपर्टी डीलर'),
  ('office.estate_agent', 'ja', '不動産'),
  ('office.estate_agent', 'pt-BR', 'Imobiliária'),
  ('office.estate_agent', 'ru', 'Агентство недвижимости'),
  ('office.estate_agent', 'zh-Hans', '房产中介'),
  ('office.lawyer', 'en', 'Lawyer'),
  ('office.lawyer', 'ar', 'مكتب محاماة'),
  ('office.lawyer', 'bn', 'আইনজীবী'),
  ('office.lawyer', 'ca', 'Advocat'),
  ('office.lawyer', 'de', 'Rechtsanwalt'),
  ('office.lawyer', 'es', 'Abogado'),
  ('office.lawyer', 'fr', 'Avocat'),
  ('office.lawyer', 'hi', 'वकील'),
  ('office.lawyer', 'ja', '法律事務所'),
  ('office.lawyer', 'pt-BR', 'Advogado'),
  ('office.lawyer', 'ru', 'Юрист'),
  ('office.lawyer', 'zh-Hans', '律师事务所'),
  ('office.insurance', 'en', 'Insurance'),
  ('office.insurance', 'ar', 'تأمين'),
  ('office.insurance', 'bn', 'বিমা'),
  ('office.insurance', 'ca', 'Assegurances'),
  ('office.insurance', 'de', 'Versicherung'),
  ('office.insurance', 'es', 'Seguros'),
  ('office.insurance', 'fr', 'Assurances'),
  ('office.insurance', 'hi', 'बीमा'),
  ('office.insurance', 'ja', '保険'),
  ('office.insurance', 'pt-BR', 'Seguros'),
  ('office.insurance', 'ru', 'Страхование'),
  ('office.insurance', 'zh-Hans', '保险'),
  ('craft', 'en', 'Trades'),
  ('craft', 'ar', 'حرف ومهن'),
  ('craft', 'bn', 'কারিগরি ব্যবসা'),
  ('craft', 'ca', 'Oficis'),
  ('craft', 'de', 'Handwerk'),
  ('craft', 'es', 'Oficios'),
  ('craft', 'fr', 'Artisans'),
  ('craft', 'hi', 'कारीगर और कारोबार'),
  ('craft', 'ja', '工房・職人'),
  ('craft', 'pt-BR', 'Ofícios'),
  ('craft', 'ru', 'Ремёсла'),
  ('craft', 'zh-Hans', '手工作坊'),
  ('craft.brewery', 'en', 'Brewery'),
  ('craft.brewery', 'ar', 'مصنع جعة'),
  ('craft.brewery', 'bn', 'ব্রিউয়ারি'),
  ('craft.brewery', 'ca', 'Fàbrica de cervesa'),
  ('craft.brewery', 'de', 'Brauerei'),
  ('craft.brewery', 'es', 'Cervecera'),
  ('craft.brewery', 'fr', 'Brasserie artisanale'),
  ('craft.brewery', 'hi', 'ब्रूअरी'),
  ('craft.brewery', 'ja', '醸造所'),
  ('craft.brewery', 'pt-BR', 'Cervejaria'),
  ('craft.brewery', 'ru', 'Пивоварня'),
  ('craft.brewery', 'zh-Hans', '酿酒厂'),
  ('craft.winery', 'en', 'Winery'),
  ('craft.winery', 'ar', 'مصنع نبيذ'),
  ('craft.winery', 'bn', 'ওয়াইনারি'),
  ('craft.winery', 'ca', 'Celler'),
  ('craft.winery', 'de', 'Weingut'),
  ('craft.winery', 'es', 'Bodega'),
  ('craft.winery', 'fr', 'Domaine viticole'),
  ('craft.winery', 'hi', 'वाइनरी'),
  ('craft.winery', 'ja', 'ワイナリー'),
  ('craft.winery', 'pt-BR', 'Vinícola'),
  ('craft.winery', 'ru', 'Винодельня'),
  ('craft.winery', 'zh-Hans', '酒庄');
--> statement-breakpoint
INSERT INTO "place_category_osm_tags" ("tag", "category_key") VALUES
  ('amenity=restaurant', 'food.restaurant'),
  ('amenity=fast_food', 'food.fast_food'),
  ('amenity=food_court', 'food.fast_food'),
  ('amenity=cafe', 'food.cafe'),
  ('shop=coffee', 'food.cafe'),
  ('shop=tea', 'food.cafe'),
  ('amenity=bar', 'food.bar'),
  ('amenity=pub', 'food.pub'),
  ('amenity=biergarten', 'food.pub'),
  ('amenity=nightclub', 'food.nightclub'),
  ('amenity=ice_cream', 'food.ice_cream'),
  ('shop=ice_cream', 'food.ice_cream'),
  ('shop=bakery', 'food.bakery'),
  ('shop=pastry', 'food.bakery'),
  ('shop=confectionery', 'food.confectionery'),
  ('shop=chocolate', 'food.confectionery'),
  ('shop=*', 'shop'),
  ('shop=supermarket', 'shop.supermarket'),
  ('shop=wholesale', 'shop.supermarket'),
  ('shop=convenience', 'shop.convenience'),
  ('shop=greengrocer', 'shop.greengrocer'),
  ('shop=butcher', 'shop.butcher'),
  ('shop=seafood', 'shop.butcher'),
  ('shop=deli', 'shop.deli'),
  ('shop=delicatessen', 'shop.deli'),
  ('shop=cheese', 'shop.deli'),
  ('amenity=marketplace', 'shop.marketplace'),
  ('shop=alcohol', 'shop.alcohol'),
  ('shop=wine', 'shop.alcohol'),
  ('shop=beverages', 'shop.alcohol'),
  ('shop=books', 'shop.books'),
  ('shop=clothes', 'shop.clothes'),
  ('shop=boutique', 'shop.clothes'),
  ('shop=bag', 'shop.clothes'),
  ('shop=fashion_accessories', 'shop.clothes'),
  ('shop=shoes', 'shop.shoes'),
  ('shop=jewelry', 'shop.jewelry'),
  ('shop=watches', 'shop.jewelry'),
  ('shop=gift', 'shop.gift'),
  ('shop=souvenir', 'shop.gift'),
  ('shop=florist', 'shop.florist'),
  ('shop=garden_centre', 'shop.florist'),
  ('shop=hardware', 'shop.hardware'),
  ('shop=doityourself', 'shop.hardware'),
  ('shop=paint', 'shop.hardware'),
  ('shop=furniture', 'shop.furniture'),
  ('shop=interior_decoration', 'shop.furniture'),
  ('shop=houseware', 'shop.furniture'),
  ('shop=bed', 'shop.furniture'),
  ('shop=carpet', 'shop.furniture'),
  ('shop=curtain', 'shop.furniture'),
  ('shop=lamps', 'shop.furniture'),
  ('shop=electronics', 'shop.electronics'),
  ('shop=mobile_phone', 'shop.electronics'),
  ('shop=computer', 'shop.electronics'),
  ('shop=hifi', 'shop.electronics'),
  ('shop=video_games', 'shop.electronics'),
  ('shop=camera', 'shop.electronics'),
  ('shop=beauty', 'shop.beauty'),
  ('shop=cosmetics', 'shop.beauty'),
  ('shop=perfumery', 'shop.beauty'),
  ('shop=perfume', 'shop.beauty'),
  ('shop=hairdresser', 'shop.hairdresser'),
  ('shop=barber', 'shop.hairdresser'),
  ('shop=optician', 'shop.optician'),
  ('shop=hearing_aids', 'shop.optician'),
  ('shop=chemist', 'shop.chemist'),
  ('shop=department_store', 'shop.department_store'),
  ('shop=mall', 'shop.department_store'),
  ('shop=variety_store', 'shop.department_store'),
  ('shop=sports', 'shop.sports'),
  ('shop=outdoor', 'shop.sports'),
  ('shop=bicycle', 'shop.bicycle'),
  ('shop=music', 'shop.music'),
  ('shop=musical_instrument', 'shop.music'),
  ('shop=toys', 'shop.toys'),
  ('shop=stationery', 'shop.stationery'),
  ('shop=copyshop', 'shop.stationery'),
  ('shop=newsagent', 'shop.newsagent'),
  ('shop=kiosk', 'shop.newsagent'),
  ('shop=tobacco', 'shop.tobacco'),
  ('shop=e-cigarette', 'shop.tobacco'),
  ('shop=pet', 'shop.pet'),
  ('shop=laundry', 'shop.laundry'),
  ('shop=dry_cleaning', 'shop.laundry'),
  ('shop=second_hand', 'shop.second_hand'),
  ('shop=charity', 'shop.second_hand'),
  ('shop=antiques', 'shop.second_hand'),
  ('shop=art', 'shop.art'),
  ('shop=frame', 'shop.art'),
  ('shop=craft', 'shop.art'),
  ('shop=travel_agency', 'shop.travel_agency'),
  ('tourism=hotel', 'lodging.hotel'),
  ('tourism=motel', 'lodging.hotel'),
  ('tourism=hostel', 'lodging.hostel'),
  ('building=dormitory', 'lodging.hostel'),
  ('tourism=guest_house', 'lodging.guest_house'),
  ('tourism=bed_and_breakfast', 'lodging.guest_house'),
  ('tourism=apartment', 'lodging.apartment'),
  ('tourism=chalet', 'lodging.apartment'),
  ('tourism=camp_site', 'lodging.camping'),
  ('tourism=caravan_site', 'lodging.camping'),
  ('tourism=alpine_hut', 'lodging.hut'),
  ('tourism=wilderness_hut', 'lodging.hut'),
  ('leisure=*', 'leisure'),
  ('leisure=park', 'leisure.park'),
  ('leisure=garden', 'leisure.garden'),
  ('leisure=playground', 'leisure.playground'),
  ('leisure=dog_park', 'leisure.dog_park'),
  ('tourism=picnic_site', 'leisure.picnic_site'),
  ('leisure=nature_reserve', 'leisure.nature_reserve'),
  ('leisure=beach_resort', 'leisure.beach'),
  ('leisure=swimming_area', 'leisure.beach'),
  ('leisure=marina', 'leisure.marina'),
  ('waterway=dock', 'leisure.marina'),
  ('landuse=reservoir', 'leisure.water'),
  ('landuse=basin', 'leisure.water'),
  ('tourism=theme_park', 'leisure.amusement'),
  ('leisure=amusement_arcade', 'leisure.amusement'),
  ('leisure=escape_game', 'leisure.amusement'),
  ('leisure=bowling_alley', 'leisure.amusement'),
  ('leisure=water_park', 'leisure.amusement'),
  ('leisure=fitness_centre', 'leisure.fitness'),
  ('leisure=fitness_station', 'leisure.fitness'),
  ('sport=*', 'sport'),
  ('leisure=sports_centre', 'sport.centre'),
  ('leisure=sports_hall', 'sport.centre'),
  ('leisure=pitch', 'sport.pitch'),
  ('leisure=track', 'sport.pitch'),
  ('leisure=stadium', 'sport.stadium'),
  ('leisure=swimming_pool', 'sport.swimming'),
  ('sport=swimming', 'sport.swimming'),
  ('leisure=golf_course', 'sport.golf'),
  ('leisure=miniature_golf', 'sport.golf'),
  ('sport=golf', 'sport.golf'),
  ('leisure=ice_rink', 'sport.ice_rink'),
  ('leisure=horse_riding', 'sport.horse_riding'),
  ('sport=equestrian', 'sport.horse_riding'),
  ('sport=climbing', 'sport.climbing'),
  ('landuse=winter_sports', 'sport.skiing'),
  ('sport=skiing', 'sport.skiing'),
  ('tourism=*', 'culture'),
  ('tourism=museum', 'culture.museum'),
  ('tourism=gallery', 'culture.gallery'),
  ('amenity=arts_centre', 'culture.gallery'),
  ('amenity=theatre', 'culture.theatre'),
  ('amenity=cinema', 'culture.cinema'),
  ('amenity=music_venue', 'culture.music_venue'),
  ('amenity=concert_hall', 'culture.music_venue'),
  ('tourism=attraction', 'culture.attraction'),
  ('tourism=viewpoint', 'culture.viewpoint'),
  ('tourism=artwork', 'culture.artwork'),
  ('tourism=zoo', 'culture.zoo'),
  ('tourism=aquarium', 'culture.aquarium'),
  ('tourism=information', 'culture.information'),
  ('historic=*', 'culture.historic'),
  ('historic=monument', 'culture.monument'),
  ('historic=memorial', 'culture.monument'),
  ('historic=castle', 'culture.castle'),
  ('historic=fort', 'culture.castle'),
  ('historic=ruins', 'culture.castle'),
  ('historic=archaeological_site', 'culture.archaeological_site'),
  ('highway=bus_stop', 'transport.bus_stop'),
  ('amenity=bus_station', 'transport.bus_station'),
  ('railway=station', 'transport.rail_station'),
  ('railway=halt', 'transport.rail_station'),
  ('railway=tram_stop', 'transport.tram_stop'),
  ('aerialway=station', 'transport.aerialway'),
  ('amenity=ferry_terminal', 'transport.ferry_terminal'),
  ('amenity=taxi', 'transport.taxi'),
  ('amenity=bicycle_rental', 'transport.bicycle_rental'),
  ('amenity=car_rental', 'transport.car_rental'),
  ('amenity=car_sharing', 'transport.car_rental'),
  ('amenity=fuel', 'vehicle.fuel'),
  ('amenity=charging_station', 'vehicle.charging'),
  ('amenity=parking', 'vehicle.parking'),
  ('amenity=parking_entrance', 'vehicle.parking'),
  ('shop=car_repair', 'vehicle.repair'),
  ('shop=car_parts', 'vehicle.repair'),
  ('shop=tyres', 'vehicle.repair'),
  ('shop=car', 'vehicle.dealer'),
  ('amenity=car_wash', 'vehicle.car_wash'),
  ('shop=motorcycle', 'vehicle.motorcycle'),
  ('amenity=hospital', 'health.hospital'),
  ('amenity=clinic', 'health.clinic'),
  ('amenity=doctors', 'health.doctor'),
  ('amenity=dentist', 'health.dentist'),
  ('amenity=pharmacy', 'health.pharmacy'),
  ('amenity=veterinary', 'health.veterinary'),
  ('amenity=nursing_home', 'health.care_home'),
  ('amenity=social_facility', 'health.care_home'),
  ('amenity=school', 'education.school'),
  ('amenity=kindergarten', 'education.kindergarten'),
  ('amenity=childcare', 'education.kindergarten'),
  ('amenity=university', 'education.university'),
  ('amenity=college', 'education.university'),
  ('amenity=library', 'education.library'),
  ('amenity=language_school', 'education.training'),
  ('amenity=driving_school', 'education.training'),
  ('amenity=music_school', 'education.training'),
  ('amenity=townhall', 'civic.townhall'),
  ('amenity=courthouse', 'civic.courthouse'),
  ('amenity=police', 'civic.police'),
  ('amenity=fire_station', 'civic.fire_station'),
  ('amenity=post_office', 'civic.post_office'),
  ('amenity=post_box', 'civic.post_box'),
  ('amenity=parcel_locker', 'civic.post_box'),
  ('amenity=community_centre', 'civic.community_centre'),
  ('amenity=social_centre', 'civic.community_centre'),
  ('leisure=hackerspace', 'civic.community_centre'),
  ('amenity=embassy', 'civic.embassy'),
  ('office=diplomatic', 'civic.embassy'),
  ('amenity=toilets', 'civic.toilets'),
  ('landuse=cemetery', 'civic.cemetery'),
  ('amenity=grave_yard', 'civic.cemetery'),
  ('amenity=bank', 'finance.bank'),
  ('amenity=atm', 'finance.atm'),
  ('amenity=bureau_de_change', 'finance.exchange'),
  ('amenity=place_of_worship', 'worship'),
  ('amenity=monastery', 'worship'),
  ('amenity=*', 'services'),
  ('office=*', 'office'),
  ('amenity=coworking_space', 'office.coworking'),
  ('office=coworking', 'office.coworking'),
  ('office=company', 'office.company'),
  ('office=government', 'office.government'),
  ('office=estate_agent', 'office.estate_agent'),
  ('office=lawyer', 'office.lawyer'),
  ('office=notary', 'office.lawyer'),
  ('office=insurance', 'office.insurance'),
  ('craft=*', 'craft'),
  ('craft=brewery', 'craft.brewery'),
  ('craft=distillery', 'craft.brewery'),
  ('craft=winery', 'craft.winery');

--> statement-breakpoint
CREATE FUNCTION "place_categories_english_label_guard"() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  subject text;
BEGIN
  IF TG_TABLE_NAME = 'place_categories' THEN
    subject := NEW."key";
  ELSE
    subject := OLD."category_key";
  END IF;
  IF EXISTS (SELECT 1 FROM "place_categories" WHERE "key" = subject)
     AND NOT EXISTS (
       SELECT 1 FROM "place_category_labels" WHERE "category_key" = subject AND "language" = 'en'
     ) THEN
    RAISE EXCEPTION 'place category % has no English label', subject
      USING ERRCODE = 'check_violation', CONSTRAINT = 'place_categories_english_label',
            TABLE = TG_TABLE_NAME;
  END IF;
  RETURN NULL;
END
$$;
--> statement-breakpoint
CREATE CONSTRAINT TRIGGER "place_categories_english_label"
  AFTER INSERT ON "place_categories"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION "place_categories_english_label_guard"();
--> statement-breakpoint
CREATE CONSTRAINT TRIGGER "place_category_labels_english_label"
  AFTER DELETE OR UPDATE OF "category_key", "language" ON "place_category_labels"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION "place_categories_english_label_guard"();
--> statement-breakpoint
CREATE FUNCTION "place_categories_key_guard"() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'UPDATE' THEN
    RAISE EXCEPTION 'place category % cannot be renamed: a key is immutable', OLD."key"
      USING ERRCODE = 'restrict_violation', CONSTRAINT = 'place_categories_key_immutable',
            TABLE = 'place_categories';
  END IF;
  IF EXISTS (SELECT 1 FROM "places" WHERE "categories" @> ARRAY[OLD."key"]) THEN
    RAISE EXCEPTION 'place category % is carried by a place and cannot be deleted', OLD."key"
      USING ERRCODE = 'restrict_violation', CONSTRAINT = 'place_categories_in_use',
            TABLE = 'place_categories';
  END IF;
  RETURN OLD;
END
$$;
--> statement-breakpoint
CREATE TRIGGER "place_categories_key_guard"
  BEFORE DELETE OR UPDATE OF "key" ON "place_categories"
  FOR EACH ROW EXECUTE FUNCTION "place_categories_key_guard"();
--> statement-breakpoint
CREATE FUNCTION "places_categories_taxonomy_guard"() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  previous text[] := '{}';
  refused text;
BEGIN
  IF TG_OP = 'UPDATE' THEN
    previous := OLD."categories";
  END IF;
  SELECT candidate INTO refused
  FROM unnest(NEW."categories") AS candidate
  WHERE (candidate IS NULL OR candidate <> ALL (previous))
    AND NOT EXISTS (
      SELECT 1 FROM "place_categories" AS category
      WHERE category."key" = candidate AND category."status" = 'active'
    )
  LIMIT 1;
  IF FOUND THEN
    RAISE EXCEPTION 'places.categories: % is not an active place category', coalesce(refused, 'NULL')
      USING ERRCODE = 'check_violation', CONSTRAINT = 'places_categories_taxonomy_guard',
            TABLE = 'places', COLUMN = 'categories';
  END IF;
  RETURN NEW;
END
$$;
--> statement-breakpoint
SET LOCAL lock_timeout = '5s';
--> statement-breakpoint
CREATE TRIGGER "places_categories_taxonomy_insert"
  BEFORE INSERT ON "places"
  FOR EACH ROW WHEN (cardinality(NEW."categories") > 0)
  EXECUTE FUNCTION "places_categories_taxonomy_guard"();
--> statement-breakpoint
CREATE TRIGGER "places_categories_taxonomy_update"
  BEFORE UPDATE OF "categories" ON "places"
  FOR EACH ROW WHEN (NEW."categories" IS DISTINCT FROM OLD."categories")
  EXECUTE FUNCTION "places_categories_taxonomy_guard"();
